import type { CatalogOfferingSpec } from "./catalog";

export const CATALOG_OFFERINGS: CatalogOfferingSpec[] = [
  { model: "claude-fable-5", provider: "opencode-zen" },
  { model: "claude-fable-5", provider: "anthropic-api" },
  { model: "claude-sonnet-5", provider: "opencode-zen" },
  { model: "claude-sonnet-5", provider: "anthropic-api" },
  { model: "claude-sonnet-4-6", provider: "opencode-zen" },
  { model: "claude-sonnet-4-6", provider: "anthropic-api" },
  { model: "claude-opus-4-8", provider: "opencode-zen" },
  { model: "claude-opus-4-8", provider: "anthropic-api" },
  { model: "claude-haiku-4-5", provider: "opencode-zen" },
  { model: "claude-haiku-4-5-20251001", provider: "anthropic-api" },
  { model: "gpt-5.5", provider: "opencode-zen" },
  { model: "gpt-5.5", provider: "OpenAI" },
  { model: "gpt-5.4", provider: "opencode-zen" },
  { model: "gpt-5.4", provider: "OpenAI" },
  { model: "gpt-5.4-mini", provider: "opencode-zen" },
  { model: "gpt-5.4-mini", provider: "OpenAI" },
  { model: "gpt-5.4-nano", provider: "opencode-zen" },
  { model: "gpt-4.1", provider: "OpenAI" },
  { model: "gemini-3.5-flash", provider: "opencode-zen" },
  { model: "gemini-3.5-flash", provider: "google-ai" },
  { model: "gemini-3.1-pro", provider: "opencode-zen" },
  { model: "gemini-3.1-pro", provider: "google-ai" },
  { model: "gemini-2.5-flash", provider: "google-ai" },
  { model: "gemini-2.5-pro", provider: "google-ai" },
  { model: "deepseek-v4-flash", provider: "opencode-zen" },
  { model: "deepseek-v4-pro", provider: "opencode-zen" },
  { model: "kimi-k2.6", provider: "opencode-zen" },
  { model: "glm-5.2", provider: "opencode-zen" },
  { model: "grok-4.5", provider: "opencode-zen" },
  { model: "deepseek-ai/DeepSeek-V4-Flash", provider: "near-ai" },
  { model: "near-ai/llama-3.1-70b-instruct", provider: "near-ai" },
  { model: "near-ai/llama-3.3-70b-instruct", provider: "near-ai" },
  { model: "near-ai/qwen-2.5-72b-instruct", provider: "near-ai" },
  { model: "near-ai/deepseek-r1", provider: "near-ai" },
];
