import type { CatalogOfferingSpec } from './catalog';

export const CATALOG_OFFERINGS: CatalogOfferingSpec[] = [
  { model: 'deepseek-v4-flash', provider: 'opencode-zen' },
  { model: 'deepseek-v3', provider: 'opencode-zen' },
  { model: 'deepseek-r1', provider: 'opencode-zen' },
  { model: 'claude-sonnet-4-6', provider: 'opencode-zen' },
  { model: 'claude-sonnet-4-6', provider: 'anthropic-api' },
  { model: 'claude-opus-4-8', provider: 'opencode-zen' },
  { model: 'claude-opus-4-8', provider: 'anthropic-api' },
  { model: 'claude-haiku-4-5-20251001', provider: 'opencode-zen' },
  { model: 'claude-haiku-4-5-20251001', provider: 'anthropic-api' },
  { model: 'gpt-4o', provider: 'opencode-zen' },
  { model: 'gpt-4o', provider: 'OpenAI' },
  { model: 'gpt-4o-mini', provider: 'opencode-zen' },
  { model: 'gpt-4o-mini', provider: 'OpenAI' },
  { model: 'gemini-2.0-flash', provider: 'opencode-zen' },
  { model: 'gemini-2.0-flash', provider: 'google-ai' },
  { model: 'o3', provider: 'opencode-zen' },
  { model: 'o3', provider: 'OpenAI' },
  { model: 'o4-mini', provider: 'opencode-zen' },
  { model: 'o4-mini', provider: 'OpenAI' },
  { model: 'gpt-4.1', provider: 'OpenAI' },
  { model: 'near-ai/llama-3.1-70b-instruct', provider: 'near-ai' },
  { model: 'near-ai/llama-3.3-70b-instruct', provider: 'near-ai' },
  { model: 'near-ai/qwen-2.5-72b-instruct', provider: 'near-ai' },
  { model: 'near-ai/deepseek-r1', provider: 'near-ai' },
  { model: 'gemini-2.5-flash', provider: 'google-ai' },
  { model: 'gemini-2.5-pro', provider: 'google-ai' },
];
