// Every user-facing word the conversation surface prints, in one place.
// The package underneath calls everything a "channel" — a `kind` string of
// "channel" or "chat" — but the app decides what a human reads: a
// "workbench" is the product word for a conversation with an agent (each
// one its own tenancy), and "Pinned" survives for the pinned,
// broadcast-style kind (its own creation step is dead — see
// `new-channel-dialog.tsx`'s module doc — but the strings still exist for a
// future caller that reaches it). Nothing in the chat/* components inlines
// its own copy; it imports from here.

export const CHAT_STRINGS = {
  channelsSectionLabel: "Pinned",
  chatsSectionLabel: "Workbenches",
  newChannelAction: "New conversation",
  newChannelDialogTitle: "New conversation",
  newChannelDialogDescription:
    "Give it a name and choose whether it is a pinned, shared conversation or an ordinary workbench.",
  newChannelNameLabel: "Name",
  newChannelNamePlaceholder: "e.g. Launch planning",
  newChannelKindLabel: "Type",
  newChannelKindChannel: "Pinned",
  newChannelKindChannelDesc: "Pinned, for the whole workbench",
  newChannelKindChat: "Workbench",
  newChannelKindChatDesc: "A direct conversation with an agent or teammate",
  newChannelPurposeLabel: "Purpose (optional)",
  newChannelPurposePlaceholder: "What is this for?",
  newChannelSubmit: "Create",
  newChannelSubmitting: "Creating…",
  newChannelCancel: "Cancel",
  newChannelBack: "Back",
  newChannelNext: "Next",
  newChannelStepKindLabel: "Kind",
  newChannelStepKindGuidance:
    "Choose a pinned conversation shared with everyone, or a direct workbench.",
  newChannelStepDetailsLabel: "Details",
  newChannelStepChannelGuidance: "Name it and add an optional purpose.",
  newChannelStepChatGuidance:
    "Pick an agent to start a workbench with, or a teammate to talk to directly — the workbench's name defaults to theirs, and you can always rename it.",
  newChatDialogTitle: "New workbench",
  newChatDialogDescription:
    "Every pick starts a new workbench — an agent is a starting point, not a conversation you're reopening.",
  newChatNameLabel: "Name (optional)",
  newChatNamePlaceholder: "Defaults to the agent's name",
  newChatCounterpartTabAgent: "Agents",
  newChatCounterpartTabPerson: "People",
  newChatAgentLabel: "Agent",
  newChatAgentComboboxPlaceholder: "Search or create agents",
  newChatAgentComboboxEmpty: "No agents match.",
  newChatAgentLoadError: "Couldn't load agents",
  newChatAgentEmptyTitle: "No agents available",
  newChatAgentEmptyDescription:
    "Add an agent here before opening a workbench with it.",
  newChatPersonLabel: "Person",
  newChatPersonLoadError: "Couldn't load teammates",
  newChatPersonEmptyTitle: "No teammates available",
  newChatPersonEmptyDescription:
    "Invite teammates here before opening a direct workbench with one.",
  newChatCreateAgentAffordance: "Create new agent",
  newChannelMissingAgentError: "Choose an agent or teammate to get started.",
  newChannelSelfDmError: "You can't open a workbench with yourself.",
  noChannelsTitle: "No workbenches yet",
  noChannelsDescription: "Create one to get started.",
  noChatSelectedTitle: "Select a conversation",
  noChatSelectedDescription:
    "Choose a workbench from the sidebar, or create a new one.",
  couldNotLoadChannels: "workbenches",
  couldNotLoadMessages: "messages",
  channelNotFoundTitle: "This workbench isn't here anymore",
  channelNotFoundDescription:
    "It may have been deleted, or the link is out of date.",
  channelNotFoundAction: "Back to workbenches",
  composerPlaceholder:
    "Send a message… use @ to mention an agent, / for commands",
  composerPlaceholderChat: (name: string) => `Message ${name}… / for commands`,
  composerSend: "Send",
  composerSending: "Sending…",
  composerAttach: "Attach files",
  composerAttachmentsLabel: "Selected attachments",
  composerRemoveAttachment: (name: string) => `Remove ${name}`,
  composerPreparing: "Preparing attachments…",
  composerAttachmentCountError: (max: number) =>
    `You can attach at most ${max} files.`,
  composerAttachmentPerFileError: (name: string, maxMiB: number) =>
    `"${name}" is too large (max ${maxMiB} MB per file).`,
  composerAttachmentTotalError: (maxMiB: number) =>
    `Those files total more than ${maxMiB} MB.`,
  composerAttachmentReadError: "Couldn't read one of those files — try again.",
  filePartLabel: "Attachment",
  emptyTimelineTitle: "No messages yet",
  emptyTimelineDescription: "Say something to get the conversation going.",
  mentionEmpty: "No matching agents",
  composerSlashEmpty: "No matching commands",
  composerSummarizeNoAgentError:
    "No agent in this conversation to summarize for — invite one first.",
  composerHelpTitle: "Slash commands",
  composerHelpNote: "Not sent as a message",
  composerHelpClose: "Close",
  runRoutineUnavailable: "Open Routines to run one",
  unnamedChannel: "Untitled conversation",
  unnamedRun: "Untitled agent",
  fallbackPartLabel: (kind: string) => `[${kind}]`,
  senderYou: "You",
  senderFallbackMember: "Member",
  agentBadgeLabel: "Agent",
  legacyBadgeLabel: "Legacy",
  eventAgentJoined: (handle: string) => `@${handle} joined`,
  eventAgentJoinedUnknown: "An agent joined",
  eventMembershipChanged: "Membership updated",
  eventSettingsChanged: "Settings updated",
  eventBlockResponsePoll: "A vote was recorded",
  eventBlockResponseForm: "A form was submitted",
  eventGeneric: (event: string) => event.replace(/[.\-_]+/g, " "),
  inviteAgentAction: "Invite agent",
  inviteAgentDialogTitle: "Invite an agent",
  inviteAgentDialogDescription:
    "Launch one of your workbench's agents into this conversation.",
  inviteAgentEmptyTitle: "No agents to invite",
  inviteAgentEmptyDescription:
    "Add an agent to this workbench before inviting it here.",
  inviteAgentLoadError: "Couldn't load invitable agents",
  inviteAgentInviting: "Inviting…",
  inviteAgentInviteError: "Couldn't invite that agent — try again.",
  inviteAgentConflictError: "This workbench already has its agent.",
  newChannelCreateError: "Couldn't create that — try again.",
  forkThreadAction: "Fork",
  forkThreadError: "Couldn't fork that message into a thread — try again.",
  replyInThreadAction: "Reply in thread",
  messageActionsMenuLabel: "Message actions",
  copyTextAction: "Copy text",
  copyTextCopiedToast: "Copied",
  copyTextError: "Couldn't copy — try again.",
  forkThreadOriginBanner: "Forked from a message in",
  channelCreatedToast: (title: string) => `Created · ${title}`,
  channelRenamedToast: (title: string) => `Renamed to ${title}`,
  channelPinnedToast: (pinned: boolean, title: string) =>
    pinned ? `Pinned ${title}` : `Unpinned ${title}`,
  reactionChipLabel: (emoji: string, count: number) =>
    `React with ${emoji} (${count})`,
  reactionAddAction: "Add reaction",
  reactionPickerLabel: "Choose a reaction",
  reactionPickerOptionLabel: (emoji: string) => `React with ${emoji}`,
  reactionToggleError: "Couldn't update that reaction — try again.",
  pinMessageAction: "Pin message",
  unpinMessageAction: "Unpin message",
  pinMessageError: "Couldn't pin that message — try again.",
  unpinMessageError: "Couldn't unpin that message — try again.",
  pinnedStripLabel: "Pinned messages",
  pinnedStripEmptyPreview: "Pinned message",
  pinnedStripJumpAction: (preview: string) => `Jump to: ${preview}`,
  sendFailedMessage: "Couldn't send — retry",
  fallbackPartUnsupported: "Unsupported content",
  blockUnsupportedTitle: "Unsupported block",
  blockUnsupportedBody: (type: string) =>
    `This "${type}" block can't be shown here yet.`,
  blockApproveAction: "Approve",
  blockDenyAction: "Deny",
  blockRiskLabel: (risk: "low" | "medium" | "high") =>
    risk === "low"
      ? "Low risk"
      : risk === "medium"
        ? "Medium risk"
        : "High risk",
  blockFormSubmit: "Submit",
  blockApproveStatusLoading: "Checking status…",
  blockApproveStatusApproved: "Approved",
  blockApproveStatusRejected: "Denied",
  blockApproveStatusTimeout: "Timed out",
  blockApproveStatusExpired: "Expired",
  blockApproveStatusNotFound: "This approval could not be found.",
  blockApproveStatusLoadError: "Couldn't load this approval's status.",
  blockApproveSpectatorNote:
    "Only an approver on this workbench can act on this.",
  blockApproveUndeterminedNote:
    "Your access to act on this could not be confirmed yet — try Approve or Deny to find out.",
  blockApproveApproving: "Approving…",
  blockApproveRejecting: "Denying…",
  blockApproveActionForbidden: "You do not have permission to act on this.",
  blockApproveActionError: "Couldn't reach the approval — try again.",
  blockApprovePlatformRequestedBy: (agentName: string) =>
    `Requested by ${agentName}`,
  blockApproveAgentNoteLabel: "Agent's note",
  blockApproveConflictNote:
    "Someone else already resolved this while you were deciding.",
  blockPollVoteCount: (count: number) =>
    count === 1 ? "1 vote" : `${count} votes`,
  blockPollYourVote: "Your vote",
  blockPollChangeVote: "Change vote",
  blockPollVoteError: "Couldn't record your vote — try again.",
  blockFormSubmitting: "Submitting…",
  blockFormSubmitted: "Submitted",
  blockFormEdit: "Edit response",
  blockFormSubmitError: "Couldn't submit — try again.",
  blockFormFieldRequired: "This field is required.",
  dayDividerToday: "Today",
  dayDividerYesterday: "Yesterday",
  typingIndicator: (label: string) => `${label} is typing`,
  rowMenuLabel: "Conversation actions",
  rowMenuRename: "Rename",
  rowMenuPin: "Pin",
  rowMenuUnpin: "Unpin",
  rowMenuSettings: "Settings",
  renameCancel: "Escape to cancel",
  channelSettingsAction: "Settings",
  channelSettingsBreadcrumbLabel: "Settings breadcrumb",
  channelSettingsBreadcrumbCurrent: "Settings",
  channelSettingsNavLabel: "Settings sections",
  channelSettingsGroupShared: "Shared · everyone",
  channelSettingsGroupPersonal: "Personal · only you",
  channelSettingsSectionGeneral: "General",
  channelSettingsSectionMembers: "Members",
  channelSettingsSectionAgents: "Agents",
  channelSettingsSectionAssistant: "Assistant",
  channelSettingsSectionAccess: "Access",
  channelSettingsSectionNotifications: "Notifications",
  channelSettingsSectionDanger: "Danger zone",
  channelSettingsNameLabel: "Name",
  channelSettingsPurposeLabel: "Purpose",
  channelSettingsPurposePlaceholder: "What is this for?",
  channelSettingsPinnedLabel: "Pinned",
  channelSettingsPinnedDescription:
    "Pinned conversations stay at the top for the whole workbench.",
  channelSettingsContextWindowLabel: "Conversation memory",
  channelSettingsContextWindowDescription:
    "How many prior messages a mentioned agent sees as context.",
  channelSettingsUseBenchDefault: (benchDefault: number) =>
    `Use workbench default (${benchDefault})`,
  channelSettingsUseOverride: "Set a custom value for this conversation",
  channelSettingsContextWindowDisabled:
    "Disabled — mentioned agents see no history",
  channelSettingsContextWindowCustom: (count: number) =>
    `Last ${count} messages`,
  channelSettingsDeliveryTitle: "Delivery thread",
  channelSettingsDeliveryBody:
    "Routine and agent delivery always lands in a dedicated delivery thread — never the main timeline — so broadcast stays readable.",
  channelSettingsParticipantsLabel: "Participants",
  channelSettingsPeopleLabel: "People",
  channelSettingsAgentsLabel: "Agents",
  channelSettingsNoPeople: "No people here yet.",
  channelSettingsNoAgents: "No agents invited yet.",
  channelSettingsAutonomyTitle: "Autonomy",
  channelSettingsAutonomyBody:
    "Per-conversation autonomy overrides are not stored yet. Agents inherit the workbench default until that control lands.",
  channelSettingsAssistantNameLabel: "Assistant name",
  channelSettingsAssistantInstructionsLabel: "Instructions",
  channelSettingsAssistantInstructionsHint:
    "How this agent should act and what it knows to do. Applies from this agent's next reply in this conversation; other conversations with the same agent pick it up the next time their agent wakes.",
  channelSettingsAssistantLoadError: "Couldn't load this agent's instructions",
  channelSettingsAssistantSaveError: "Couldn't save these changes — try again.",
  channelSettingsAssistantSavedToast: "Instructions saved",
  channelSettingsAssistantSave: "Save",
  channelSettingsAssistantSaving: "Saving…",
  channelSettingsAssistantCancel: "Cancel",
  channelSettingsAssistantNoAgents:
    "No agents to configure in this conversation.",
  channelSettingsAssistantCapabilitiesTitle: "Capabilities",
  channelSettingsAssistantCapabilitiesHint:
    "What this agent can use. Add a tool, skill, or model from what's available in this workbench.",
  channelSettingsAssistantNoCapabilities: "No tools, skills, or model set yet.",
  channelSettingsAssistantModelLabel: "Model",
  channelSettingsAssistantAddCapabilityLabel: "Add a capability",
  channelSettingsAssistantAddCapabilityKindTool: "Tool",
  channelSettingsAssistantAddCapabilityKindSkill: "Skill",
  channelSettingsAssistantAddCapabilityKindModel: "Model",
  channelSettingsAssistantAddCapabilityButton: "Add",
  channelSettingsAssistantAddCapabilityAdding: "Adding…",
  channelSettingsAssistantAddCapabilityError:
    "Couldn't add that — it may no longer be available.",
  channelSettingsAssistantCapabilityInventoryError:
    "Couldn't load what's available to add.",
  channelSettingsAssistantHistoryTitle: "History",
  channelSettingsAssistantHistoryHint:
    "Every change to this agent's instructions and capabilities, oldest actions first.",
  channelSettingsAssistantHistoryLoadError:
    "Couldn't load this agent's history",
  channelSettingsAssistantHistoryEmpty: "No history yet.",
  channelSettingsAssistantHistoryCurrent: "Current",
  channelSettingsAssistantHistoryRestore: "Restore",
  channelSettingsAssistantHistoryRestoring: "Restoring…",
  channelSettingsAssistantHistoryRestoreError:
    "Couldn't restore that version — try again.",
  channelSettingsAccessBody:
    "Access follows workbench grants and membership. Manage role and member grants under Workspace → Grants.",
  channelSettingsNotificationsLabel: "Notifications",
  channelSettingsNotifyAll: "All messages",
  channelSettingsNotifyMentions: "Mentions only",
  channelSettingsNotifyMute: "Mute",
  channelSettingsNotificationsHint:
    "Preference is local draft UI until per-conversation notification storage ships.",
  channelSettingsArchiveTitle: "Archive workbench",
  channelSettingsArchiveBody:
    "Archiving is not available yet. Closing this workbench would hide it from the sidebar without deleting history once the action lands.",
  channelSettingsLoadError: "Couldn't load this conversation's settings",
  channelSettingsSaveError:
    "Couldn't save this conversation's settings — try again.",
  channelSettingsSavedToast: "Settings saved",
  channelSettingsSave: "Save",
  channelSettingsSaving: "Saving…",
  channelSettingsNoParticipants: "No participants yet.",
  profileOpenAction: "Open profile",
  profileMessageAction: "Message",
  profileViewSettingsAction: "View settings",
  profileSharedChannels: "Shared workbenches",
  profilePinnedSkills: "Pinned skills",
  profileAgentStatus: "Agent",
  profileMemberStatus: "Member",
} as const;
