// Every user-facing word the chat surface prints, in one place. The package
// underneath calls everything a "channel" — a `kind` string of "channel" or
// "chat" — but the app decides what a human reads: "Channels" for the pinned,
// broadcast-style kind and "Chats" for everything else. Nothing in the chat/*
// components inlines its own copy; it imports from here.

export const CHAT_STRINGS = {
  channelsSectionLabel: "Channels",
  chatsSectionLabel: "Chats",
  newChannelAction: "New channel",
  newChannelDialogTitle: "New channel",
  newChannelDialogDescription:
    "Give it a name and choose whether it is a pinned channel or an ordinary chat.",
  newChannelNameLabel: "Name",
  newChannelNamePlaceholder: "e.g. Launch planning",
  newChannelKindLabel: "Type",
  newChannelKindChannel: "Channel",
  newChannelKindChannelDesc: "Pinned, for the whole workbench",
  newChannelKindChat: "Chat",
  newChannelKindChatDesc: "A direct conversation with an agent or teammate",
  newChannelPurposeLabel: "Purpose (optional)",
  newChannelPurposePlaceholder: "What is this channel for?",
  newChannelSubmit: "Create",
  newChannelSubmitting: "Creating…",
  newChannelCancel: "Cancel",
  newChannelBack: "Back",
  newChannelNext: "Next",
  newChannelStepKindLabel: "Kind",
  newChannelStepKindGuidance:
    "Choose a pinned channel for the whole workbench, or a direct chat.",
  newChannelStepDetailsLabel: "Details",
  newChannelStepChannelGuidance: "Name it and add an optional purpose.",
  newChannelStepChatGuidance:
    "Pick who to talk to — the chat's name defaults to theirs.",
  newChatDialogTitle: "New chat",
  newChatDialogDescription: "Pick who you want to talk to.",
  newChatNameLabel: "Name (optional)",
  newChatNamePlaceholder: "Defaults to the agent's name",
  newChatCounterpartTabAgent: "Agents",
  newChatCounterpartTabPerson: "People",
  newChatAgentLabel: "Agent",
  newChatAgentLoadError: "Couldn't load agents to chat with",
  newChatAgentEmptyTitle: "No agents available",
  newChatAgentEmptyDescription:
    "Add an agent to this workbench before starting a chat with it.",
  newChatPersonLabel: "Person",
  newChatPersonLoadError: "Couldn't load teammates to chat with",
  newChatPersonEmptyTitle: "No teammates available",
  newChatPersonEmptyDescription:
    "Invite teammates to this workbench before starting a direct chat.",
  newChannelMissingAgentError:
    "Choose an agent or teammate to start this chat.",
  newChannelSelfDmError: "You can't start a direct chat with yourself.",
  noChannelsTitle: "No channels yet",
  noChannelsDescription:
    "Create a channel to start a conversation your agents and teammates can see.",
  noChatSelectedTitle: "Select a conversation",
  noChatSelectedDescription:
    "Choose a channel or chat from the sidebar, or start a new one.",
  couldNotLoadChannels: "channels",
  couldNotLoadMessages: "messages",
  composerPlaceholder:
    "Message this channel… use @ to mention an agent, / for commands",
  composerSend: "Send",
  composerSending: "Sending…",
  composerAttach: "Attach files",
  composerAttachmentsLabel: "Selected attachments",
  composerRemoveAttachment: (name: string) => `Remove ${name}`,
  composerPreparing: "Preparing attachments…",
  composerAttachmentCountError: (max: number) =>
    `You can attach at most ${max} files.`,
  composerAttachmentPerFileError: (name: string, maxMiB: number) =>
    `"${name}" is too large (max ${maxMiB} MB per file).`,
  composerAttachmentTotalError: (maxMiB: number) =>
    `Those files total more than ${maxMiB} MB.`,
  composerAttachmentReadError: "Couldn't read one of those files — try again.",
  filePartLabel: "Attachment",
  emptyTimelineTitle: "No messages yet",
  emptyTimelineDescription: "Say something to get the conversation going.",
  mentionEmpty: "No matching agents",
  composerSlashEmpty: "No matching commands",
  composerSummarizeNoAgentError:
    "No agent in this channel to summarize for — invite one first.",
  composerHelpTitle: "Slash commands",
  composerHelpNote: "Not sent as a message",
  composerHelpClose: "Close",
  runRoutineUnavailable: "Open Routines to run one",
  unnamedChannel: "Untitled channel",
  unnamedRun: "Untitled agent",
  fallbackPartLabel: (kind: string) => `[${kind}]`,
  senderYou: "You",
  senderFallbackMember: "Member",
  agentBadgeLabel: "Agent",
  legacyBadgeLabel: "Legacy",
  eventAgentJoined: (handle: string) => `@${handle} joined`,
  eventAgentJoinedUnknown: "An agent joined",
  eventMembershipChanged: "Channel membership updated",
  eventSettingsChanged: "Channel settings updated",
  eventBlockResponsePoll: "A vote was recorded",
  eventBlockResponseForm: "A form was submitted",
  eventGeneric: (event: string) => event.replace(/[.\-_]+/g, " "),
  inviteAgentAction: "Invite agent",
  inviteAgentDialogTitle: "Invite an agent",
  inviteAgentDialogDescription:
    "Launch one of your workbench's agents into this channel.",
  inviteAgentEmptyTitle: "No agents to invite",
  inviteAgentEmptyDescription:
    "Add an agent to this workbench before inviting it here.",
  inviteAgentLoadError: "Couldn't load invitable agents",
  inviteAgentInviting: "Inviting…",
  inviteAgentInviteError: "Couldn't invite that agent — try again.",
  inviteAgentConflictError: "This chat already has its agent.",
  newChannelCreateError: "Couldn't create that channel — try again.",
  forkThreadAction: "Fork",
  forkThreadError: "Couldn't fork that message into a thread — try again.",
  forkThreadOriginBanner: "Forked from a message in",
  channelCreatedToast: (title: string) => `Channel created · ${title}`,
  channelRenamedToast: (title: string) => `Renamed to ${title}`,
  channelPinnedToast: (pinned: boolean, title: string) =>
    pinned ? `Pinned ${title}` : `Unpinned ${title}`,
  reactionChipLabel: (emoji: string, count: number) =>
    `React with ${emoji} (${count})`,
  reactionAddAction: "Add reaction",
  reactionPickerLabel: "Choose a reaction",
  reactionPickerOptionLabel: (emoji: string) => `React with ${emoji}`,
  reactionToggleError: "Couldn't update that reaction — try again.",
  pinMessageAction: "Pin message",
  unpinMessageAction: "Unpin message",
  pinMessageError: "Couldn't pin that message — try again.",
  unpinMessageError: "Couldn't unpin that message — try again.",
  pinnedStripLabel: "Pinned messages",
  pinnedStripEmptyPreview: "Pinned message",
  pinnedStripJumpAction: (preview: string) => `Jump to: ${preview}`,
  sendFailedMessage: "Couldn't send — retry",
  fallbackPartUnsupported: "Unsupported content",
  blockUnsupportedTitle: "Unsupported block",
  blockUnsupportedBody: (type: string) =>
    `This "${type}" block can't be shown here yet.`,
  blockApproveAction: "Approve",
  blockDenyAction: "Deny",
  blockRiskLabel: (risk: "low" | "medium" | "high") =>
    risk === "low"
      ? "Low risk"
      : risk === "medium"
        ? "Medium risk"
        : "High risk",
  blockFormSubmit: "Submit",
  blockApproveStatusLoading: "Checking status…",
  blockApproveStatusApproved: "Approved",
  blockApproveStatusRejected: "Denied",
  blockApproveStatusTimeout: "Timed out",
  blockApproveStatusExpired: "Expired",
  blockApproveStatusNotFound: "This approval could not be found.",
  blockApproveStatusLoadError: "Couldn't load this approval's status.",
  blockApproveSpectatorNote:
    "Only an approver on this workbench can act on this.",
  blockApproveUndeterminedNote:
    "Your access to act on this could not be confirmed yet — try Approve or Deny to find out.",
  blockApproveApproving: "Approving…",
  blockApproveRejecting: "Denying…",
  blockApproveActionForbidden: "You do not have permission to act on this.",
  blockApproveActionError: "Couldn't reach the approval — try again.",
  blockApprovePlatformRequestedBy: (agentName: string) =>
    `Requested by ${agentName}`,
  blockApproveAgentNoteLabel: "Agent's note",
  blockApproveConflictNote:
    "Someone else already resolved this while you were deciding.",
  blockPollVoteCount: (count: number) =>
    count === 1 ? "1 vote" : `${count} votes`,
  blockPollYourVote: "Your vote",
  blockPollChangeVote: "Change vote",
  blockPollVoteError: "Couldn't record your vote — try again.",
  blockFormSubmitting: "Submitting…",
  blockFormSubmitted: "Submitted",
  blockFormEdit: "Edit response",
  blockFormSubmitError: "Couldn't submit — try again.",
  blockFormFieldRequired: "This field is required.",
  dayDividerToday: "Today",
  dayDividerYesterday: "Yesterday",
  typingIndicator: (label: string) => `${label} is typing`,
  rowMenuLabel: "Channel actions",
  rowMenuRename: "Rename",
  rowMenuPin: "Pin",
  rowMenuUnpin: "Unpin",
  rowMenuSettings: "Channel settings",
  renameCancel: "Escape to cancel",
  channelSettingsAction: "Channel settings",
  channelSettingsBreadcrumbLabel: "Channel settings breadcrumb",
  channelSettingsBreadcrumbCurrent: "Settings",
  channelSettingsNavLabel: "Channel settings sections",
  channelSettingsGroupShared: "Shared · everyone",
  channelSettingsGroupPersonal: "Personal · only you",
  channelSettingsSectionGeneral: "General",
  channelSettingsSectionMembers: "Members",
  channelSettingsSectionAgents: "Agents",
  channelSettingsSectionAssistant: "Assistant",
  channelSettingsSectionAccess: "Access",
  channelSettingsSectionNotifications: "Notifications",
  channelSettingsSectionDanger: "Danger zone",
  channelSettingsNameLabel: "Name",
  channelSettingsPurposeLabel: "Purpose",
  channelSettingsPurposePlaceholder: "What is this channel for?",
  channelSettingsPinnedLabel: "Pinned",
  channelSettingsPinnedDescription:
    "Pinned channels stay at the top for the whole workbench.",
  channelSettingsContextWindowLabel: "Conversation memory",
  channelSettingsContextWindowDescription:
    "How many prior messages a mentioned agent sees as context.",
  channelSettingsUseBenchDefault: (benchDefault: number) =>
    `Use workbench default (${benchDefault})`,
  channelSettingsUseOverride: "Set a custom value for this channel",
  channelSettingsContextWindowDisabled:
    "Disabled — mentioned agents see no history",
  channelSettingsContextWindowCustom: (count: number) =>
    `Last ${count} messages`,
  channelSettingsDeliveryTitle: "Delivery thread",
  channelSettingsDeliveryBody:
    "Routine and agent delivery always lands in a dedicated delivery thread — never the main timeline — so broadcast stays readable.",
  channelSettingsParticipantsLabel: "Participants",
  channelSettingsPeopleLabel: "People",
  channelSettingsAgentsLabel: "Agents",
  channelSettingsNoPeople: "No people in this channel yet.",
  channelSettingsNoAgents: "No agents invited yet.",
  channelSettingsAutonomyTitle: "Autonomy",
  channelSettingsAutonomyBody:
    "Per-channel autonomy overrides are not stored yet. Agents inherit the workbench default until that control lands.",
  channelSettingsAssistantNameLabel: "Assistant name",
  channelSettingsAssistantInstructionsLabel: "Instructions",
  channelSettingsAssistantInstructionsHint:
    "How this agent should act and what it knows to do. Applies from this agent's next reply in this channel; other channels with the same agent pick it up the next time their agent wakes.",
  channelSettingsAssistantLoadError: "Couldn't load this agent's instructions",
  channelSettingsAssistantSaveError: "Couldn't save these changes — try again.",
  channelSettingsAssistantSavedToast: "Instructions saved",
  channelSettingsAssistantSave: "Save",
  channelSettingsAssistantSaving: "Saving…",
  channelSettingsAssistantCancel: "Cancel",
  channelSettingsAssistantNoAgents: "No agents to configure in this channel.",
  channelSettingsAccessBody:
    "Channel access follows workbench grants and membership. Manage role and member grants under Workspace → Grants.",
  channelSettingsNotificationsLabel: "Notifications",
  channelSettingsNotifyAll: "All messages",
  channelSettingsNotifyMentions: "Mentions only",
  channelSettingsNotifyMute: "Mute",
  channelSettingsNotificationsHint:
    "Preference is local draft UI until per-channel notification storage ships.",
  channelSettingsArchiveTitle: "Archive channel",
  channelSettingsArchiveBody:
    "Archiving is not available yet. Closing this channel would hide it from the sidebar without deleting history once the action lands.",
  channelSettingsLoadError: "Couldn't load this channel's settings",
  channelSettingsSaveError:
    "Couldn't save this channel's settings — try again.",
  channelSettingsSavedToast: "Channel settings saved",
  channelSettingsSave: "Save",
  channelSettingsSaving: "Saving…",
  channelSettingsNoParticipants: "No participants yet.",
  profileOpenAction: "Open profile",
  profileMessageAction: "Message",
  profileViewSettingsAction: "View settings",
  profileSharedChannels: "Shared channels",
  profilePinnedSkills: "Pinned skills",
  profileAgentStatus: "Agent",
  profileMemberStatus: "Member",
} as const;
