// Every user-facing word the chat surface prints, in one place. The package
// underneath calls everything a "channel" — a `kind` string of "channel" or
// "chat" — but the app decides what a human reads: "Channels" for the pinned,
// broadcast-style kind and "Chats" for everything else. Nothing in the chat/*
// components inlines its own copy; it imports from here.

export const CHAT_STRINGS = {
  channelsSectionLabel: "Channels",
  chatsSectionLabel: "Chats",
  newChannelAction: "New channel",
  newChannelDialogTitle: "New channel",
  newChannelDialogDescription:
    "Give it a name and choose whether it is a pinned channel or an ordinary chat.",
  newChannelNameLabel: "Name",
  newChannelNamePlaceholder: "e.g. Launch planning",
  newChannelKindLabel: "Type",
  newChannelKindChannel: "Channel — pinned, for the whole bench",
  newChannelKindChat: "Chat — an ordinary conversation",
  newChannelSubmit: "Create",
  newChannelCancel: "Cancel",
  newChatDialogTitle: "New chat",
  newChatDialogDescription: "Pick the agent you want to talk to.",
  newChatNameLabel: "Name (optional)",
  newChatNamePlaceholder: "Defaults to the agent's handle",
  newChatAgentLabel: "Agent",
  newChatAgentLoadError: "Couldn't load agents to chat with",
  newChatAgentEmptyTitle: "No agents available",
  newChatAgentEmptyDescription:
    "Deploy a workflow definition on this bench before starting a chat with it.",
  newChannelMissingAgentError: "Choose an agent to start this chat.",
  noChannelsTitle: "No channels yet",
  noChannelsDescription:
    "Create a channel to start a conversation your agents and teammates can see.",
  noChatSelectedTitle: "Select a conversation",
  noChatSelectedDescription:
    "Choose a channel or chat from the sidebar, or start a new one.",
  couldNotLoadChannels: "channels",
  couldNotLoadMessages: "messages",
  composerPlaceholder: "Message this channel… use @ to mention an agent",
  composerSend: "Send",
  emptyTimelineTitle: "No messages yet",
  emptyTimelineDescription: "Say something to get the conversation going.",
  reconnectingMessage: "Reconnecting to the channel…",
  mentionEmpty: "No matching agents",
  unnamedChannel: "Untitled channel",
  fallbackPartLabel: (kind: string) => `[${kind}]`,
  senderYou: "You",
  senderFallbackMember: "Member",
  agentBadgeLabel: "Agent",
  eventAgentJoined: (handle: string) => `@${handle} joined`,
  eventAgentJoinedUnknown: "An agent joined",
  eventMembershipChanged: "Channel membership updated",
  eventSettingsChanged: "Channel settings updated",
  eventGeneric: (event: string) => event.replace(/[.\-_]+/g, " "),
  inviteAgentAction: "Invite agent",
  inviteAgentDialogTitle: "Invite an agent",
  inviteAgentDialogDescription:
    "Launch one of your bench's deployed agents into this channel.",
  inviteAgentEmptyTitle: "No agents to invite",
  inviteAgentEmptyDescription:
    "Deploy a workflow definition on this bench before inviting it here.",
  inviteAgentLoadError: "Couldn't load invitable agents",
  inviteAgentInviting: "Inviting…",
  inviteAgentInviteError: "Couldn't invite that agent — try again.",
  inviteAgentConflictError: "This chat already has its agent.",
  newChannelCreateError: "Couldn't create that channel — try again.",
  sendFailedMessage: "Couldn't send — retry",
  fallbackPartUnsupported: "Unsupported content",
  dayDividerToday: "Today",
  dayDividerYesterday: "Yesterday",
} as const;
