// Every user-facing word the settings surface prints, in one place. Nothing
// in the settings-ui/* components inlines its own copy; it imports from here.

export const SETTINGS_STRINGS = {
  pageTitle: "Settings",
  pageSubtitle: "Personal settings and settings shared across your workbench",
  sectionsNavLabel: "Settings sections",
  emptySectionsTitle: "Nothing to show",
  emptySectionsDescription: "No settings sections are available right now.",
  groupAccountLabel: "Personal Settings",
  groupEveryoneLabel: "Shared Settings",
  advancedSectionsSummary: "Advanced",
  advancedSectionsHint: "Roles, granular permissions, and activity history.",
  accessProbeFailedHint:
    "Couldn't check access for some sections. They'll show up here once that succeeds.",

  notificationsSectionTitle: "Notifications",
  notificationsSectionDescription: "How activity reaches you.",
  notificationsMentions: "Mentions & DMs",
  notificationsApprovals: "Approvals",
  notificationsRoutineFail: "Failed deliveries",
  notificationsSaveAction: "Save",
  notificationsSaveHonesty: "Draft only — notification choices aren't saved yet.",

  settingsSavedToast: "Settings saved",

  benchNoneSelectedTitle: "No workbench selected",
  benchNoneSelectedDescription: "Choose a workbench from the switcher first.",

  accountSectionTitle: "General",
  accountSectionDescription: "Your name and email on this workbench.",
  accountNameLabel: "Name",
  accountEmailLabel: "Email",
  accountLoadError: "your account",
  accountReadOnlyNote:
    "These details come from how you sign in. Editing them here isn't available yet.",
  accountSignOutAction: "Sign out",
  accountDetailsHeading: "Account details",
  accountCopyEmailAction: "Copy email",
  accountEmailCopiedToast: "Copied",
  accountEmailCopyError: "Couldn't copy the email",

  appearanceSectionTitle: "Appearance",
  appearanceThemeLabel: "Theme",
  themeFollowSystem: "Follow System",
  themeLight: "Light",
  themeDark: "Dark",

  generalAgentGroupTitle: "Agent",
  agentTimezoneLabel: "Timezone",
  agentTimezoneAutoDetect: (timezone: string) => `Auto-detect (${timezone})`,

  peopleSectionTitle: "People",
  peopleSectionDescription: "Everyone with a seat on this workbench.",
  peopleLoadError: "this workbench's people",
  peopleEmptyTitle: "No people yet",
  peopleEmptyDescription: "This workbench has no people with a seat yet.",
  peopleInviteRoleLabel: "Role",
  peopleInviteRoleOwner: "Owner",
  peopleInviteRoleMember: "Member",
  peopleSuspend: "Suspend",
  peopleReactivate: "Reactivate",
  peopleRemove: "Remove",
  peopleRemoveConfirm: "Remove for good?",
  peopleStatusUpdateError: "Couldn't update that person's status — try again.",
  peopleRemoveError: "Couldn't remove that person — try again.",
  peopleUnnamedAgent: "Unnamed agent",
  peopleRoleNone: "none",
  peopleKindUser: "Person",
  peopleKindAgent: "Agent",
  peopleKindWorkflow: "Workflow",
  peopleRoleChangeError: "Couldn't change that person's role — try again.",
  peopleLastOwnerError:
    "This workbench needs at least one owner — make someone else an owner first.",

  rolesSectionTitle: "Roles",
  rolesSectionDescription: "This workbench's roles and who they're assigned to.",
  rolesLoadError: "this workbench's roles",
  rolesEmptyTitle: "No roles yet",
  rolesEmptyDescription: "Create a custom role to get started.",
  rolesCreateAction: "New role",
  rolesCreateDialogTitle: "New role",
  rolesCreateDialogDescription: "Custom roles start with no grants of their own.",
  rolesNameLabel: "Name",
  rolesNamePlaceholder: "e.g. Billing",
  rolesDescriptionLabel: "Description",
  rolesCreateSubmit: "Create",
  rolesCreateCancel: "Cancel",
  rolesCreateError: "Couldn't create that role — try again.",
  rolesRenameError: "Couldn't rename that role — try again.",
  rolesDeleteError: "Couldn't delete that role — it may still be assigned to someone.",
  rolesSystemBadge: "system",
  rolesSystemImmutableNote: "System roles can't be renamed or deleted.",
  rolesRenameAction: "Rename",
  rolesRenameSave: "Save",
  rolesRenameCancel: "Cancel",
  rolesDeleteAction: "Delete",
  rolesDeleteConfirm: "Delete for good?",
  rolesAssignSectionTitle: "Assign a role",
  rolesAssignPersonLabel: "Person",
  rolesAssignRoleLabel: "Role",
  rolesAssignSubmit: "Assign",
  rolesAssignError: "Couldn't assign that role — try again.",
  rolesUnassignError: "Couldn't remove that role — try again.",
  rolesAssignmentsTitle: "Assignments",
  rolesAssignmentsEmpty: "No one has been assigned a role yet.",
  rolesUnassign: "Remove",

  grantsSectionTitle: "What agents can do",
  grantsSectionDescription:
    "What each role or person is allowed, denied, or asked about, and on what.",
  grantsLoadError: "this workbench's rules",
  grantsEmptyTitle: "No rules match these filters",
  grantsEmptyDescription: "Try clearing a filter, or create a new rule.",
  grantsCreateAction: "New rule",
  grantsCreateDialogTitle: "New rule",
  grantsCreateDialogDescription: "Set exactly one role or one person a resource and action.",
  grantsTargetTypeLabel: "Applies to",
  grantsTargetTypeRole: "A role",
  grantsTargetTypeRoleDescription: "Everyone assigned this role.",
  grantsTargetTypePrincipal: "A person, agent, or workflow",
  grantsTargetTypePrincipalDescription: "One specific account — human or machine.",
  grantsTargetLabel: "Target",
  grantsResourceLabel: "Resource",
  grantsActionLabel: "Action",
  grantsEffectLabel: "Effect",
  grantsOriginLabel: "Origin",
  grantsExpiresLabel: "Expires",
  grantsCreateSubmit: "Create",
  grantsCreateCancel: "Cancel",
  grantsCreateError: "Couldn't create that rule — try again.",
  grantsRevoke: "Revoke",
  grantsRevokeConfirm: "Revoke for good?",
  grantsRevokeError: "Couldn't revoke that rule — try again.",
  grantsFilterPrincipal: "Person",
  grantsFilterRole: "Role",
  grantsFilterResource: "Resource",
  grantsFilterEffect: "Effect",
  grantsFilterAny: "Any",
  grantsNoExpiry: "Never",
  grantCreatedToast: "Rule created",
  grantRevokedToast: "Rule revoked",

  credentialRevokedToast: "Key revoked",

  credentialsSectionTitle: "Credentials",
  credentialsSectionDescription:
    "Keys this bench's agents and workflows can use, stored through the platform's own credential store.",
  credentialsLoadError: "credentials",
  credentialsEmptyTitle: "No credentials yet",
  credentialsEmptyDescription: "Add a key below to give agents something to authenticate with.",
  credentialsNameLabel: "Name",
  credentialsTypeLabel: "Type",
  credentialsSecretLabel: "Secret",
  credentialsSecretPlaceholder: "Pasted once, never shown again",
  credentialsStatusLabel: "Status",
  credentialsCreateAction: "Add credential",
  credentialsCreateDialogTitle: "Add a credential",
  credentialsCreateDialogDescription:
    "Sealed on save — this secret is never shown again after create.",
  credentialsCreateSubmit: "Add",
  credentialsCreateCancel: "Cancel",
  credentialsCreateError: "Couldn't save that credential — try again.",
  credentialsDeleteAction: "Delete",
  credentialsDeleteConfirm: "Delete this credential for good?",
  credentialsDeleteError: "Couldn't delete that credential — try again.",

  auditSectionTitle: "Audit",
  auditSectionDescription: "Who changed what, when — orientation only.",
  auditWhen: "When",
  auditAction: "Action",
  auditActor: "Actor",
  auditTarget: "Target",
  auditEmpty: "No recent changes to show yet.",
  auditHonestyNote:
    "Current-state view, not an append-only audit log — treat as orientation, not evidence.",
} as const;
