// Every user-facing word the settings surface prints, in one place. Nothing
// in the settings-ui/* components inlines its own copy; it imports from here.

export const SETTINGS_STRINGS = {
  pageTitle: "Settings",
  pageSubtitle: "Personal settings and settings shared across your workbench",
  sectionsNavLabel: "Settings sections",
  emptySectionsTitle: "Nothing to show",
  emptySectionsDescription: "No settings sections are available right now.",
  groupAccountLabel: "Personal Settings",
  groupEveryoneLabel: "Shared Settings",
  advancedSectionsSummary: "Advanced",
  advancedSectionsHint: "Roles, granular permissions, and activity history.",
  accessProbeFailedHint:
    "Couldn't check access for some sections. They'll show up here once that succeeds.",

  notificationsSectionTitle: "Notifications",
  notificationsSectionDescription: "How activity reaches you.",
  notificationsMentions: "Mentions & DMs",
  notificationsApprovals: "Approvals",
  notificationsRoutineFail: "Failed deliveries",
  notificationsSaveAction: "Save",
  notificationsSaveHonesty: "Draft only — notification choices aren't saved yet.",

  settingsSavedToast: "Settings saved",

  benchNoneSelectedTitle: "No workbench selected",
  benchNoneSelectedDescription: "Choose a workbench from the switcher first.",

  accountSectionTitle: "General",
  accountSectionDescription: "Your name and email on this workbench.",
  accountNameLabel: "Name",
  accountEmailLabel: "Email",
  accountLoadError: "your account",
  accountReadOnlyNote:
    "These details come from how you sign in. Editing them here isn't available yet.",
  accountSignOutAction: "Sign out",
  accountDetailsHeading: "Account details",
  accountCopyEmailAction: "Copy email",
  accountEmailCopiedToast: "Copied",
  accountEmailCopyError: "Couldn't copy the email",

  peopleSectionTitle: "People",
  peopleSectionDescription: "Everyone with a seat on this workbench.",
  peopleLoadError: "this workbench's people",
  peopleEmptyTitle: "No people yet",
  peopleEmptyDescription: "This workbench has no people with a seat yet.",
  peopleInviteRoleLabel: "Role",
  peopleInviteRoleOwner: "Owner",
  peopleInviteRoleMember: "Member",
  peopleInviteAction: "Invite",
  peopleInviteDialogTitle: "Invite someone",
  peopleInviteDialogDescription: "They need an existing account on this platform to accept.",
  peopleInviteEmailLabel: "Email",
  peopleInviteSubmit: "Send invite",
  peopleInviteCancel: "Cancel",
  peopleInviteError: "Couldn't send that invite — try again.",
  peopleSuspend: "Suspend",
  peopleReactivate: "Reactivate",
  peopleRemove: "Remove",
  peopleRemoveConfirm: "Remove for good?",
  peopleStatusUpdateError: "Couldn't update that person's status — try again.",
  peopleRemoveError: "Couldn't remove that person — try again.",
  peopleUnnamedAgent: "Unnamed agent",
  peopleRoleNone: "none",
  peopleKindUser: "Person",
  peopleKindAgent: "Agent",
  peopleKindWorkflow: "Workflow",
  peopleRoleChangeError: "Couldn't change that person's role — try again.",
  peopleLastOwnerError:
    "This workbench needs at least one owner — make someone else an owner first.",

  rolesSectionTitle: "Roles",
  rolesSectionDescription: "This workbench's roles and who they're assigned to.",
  rolesLoadError: "this workbench's roles",
  rolesEmptyTitle: "No roles yet",
  rolesEmptyDescription: "Create a custom role to get started.",
  rolesCreateAction: "New role",
  rolesCreateDialogTitle: "New role",
  rolesCreateDialogDescription: "Custom roles start with no grants of their own.",
  rolesNameLabel: "Name",
  rolesNamePlaceholder: "e.g. Billing",
  rolesDescriptionLabel: "Description",
  rolesCreateSubmit: "Create",
  rolesCreateCancel: "Cancel",
  rolesCreateError: "Couldn't create that role — try again.",
  rolesRenameError: "Couldn't rename that role — try again.",
  rolesDeleteError: "Couldn't delete that role — it may still be assigned to someone.",
  rolesSystemBadge: "system",
  rolesSystemImmutableNote: "System roles can't be renamed or deleted.",
  rolesRenameAction: "Rename",
  rolesRenameSave: "Save",
  rolesRenameCancel: "Cancel",
  rolesDeleteAction: "Delete",
  rolesDeleteConfirm: "Delete for good?",
  rolesAssignSectionTitle: "Assign a role",
  rolesAssignPrincipalLabel: "Principal",
  rolesAssignRoleLabel: "Role",
  rolesAssignSubmit: "Assign",
  rolesAssignError: "Couldn't assign that role — try again.",
  rolesAssignMissingPrincipalError:
    "That account isn't on this workbench yet — agent and workflow accounts are created on their first run, not when they're deployed. Have it run once, then assign the role again.",
  rolesUnassignError: "Couldn't remove that role — try again.",
  rolesAssignmentsTitle: "Assignments",
  rolesAssignmentsEmpty: "No assignments yet.",
  rolesUnassign: "Remove",

  grantsSectionTitle: "What agents can do",
  grantsSectionDescription:
    "What each role or person is allowed, denied, or asked about, and on what.",
  grantsLoadError: "this workbench's rules",
  grantsEmptyTitle: "No rules match these filters",
  grantsEmptyDescription: "Try clearing a filter, or create a new rule.",
  grantsCreateAction: "New rule",
  grantsCreateDialogTitle: "New rule",
  grantsCreateDialogDescription: "Set exactly one role or one person a resource and action.",
  grantsTargetTypeLabel: "Applies to",
  grantsTargetTypeRole: "A role",
  grantsTargetTypeRoleDescription: "Everyone assigned this role.",
  grantsTargetTypePrincipal: "A person, agent, or workflow",
  grantsTargetTypePrincipalDescription: "One specific account — human or machine.",
  grantsTargetLabel: "Target",
  grantsResourceLabel: "Resource",
  grantsActionLabel: "Action",
  grantsEffectLabel: "Effect",
  grantsOriginLabel: "Origin",
  grantsExpiresLabel: "Expires",
  grantsCreateSubmit: "Create",
  grantsCreateCancel: "Cancel",
  grantsCreateError: "Couldn't create that rule — try again.",
  grantsRevoke: "Revoke",
  grantsRevokeConfirm: "Revoke for good?",
  grantsRevokeError: "Couldn't revoke that rule — try again.",
  grantsFilterPrincipal: "Person",
  grantsFilterRole: "Role",
  grantsFilterResource: "Resource",
  grantsFilterEffect: "Effect",
  grantsFilterAny: "Any",
  grantsNoExpiry: "Never",
  grantCreatedToast: "Rule created",
  grantRevokedToast: "Rule revoked",

  credentialRevokedToast: "Key revoked",

  credentialsSectionTitle: "Providers",
  credentialsSectionDescription: "Where this workbench's inference comes from.",
  credentialsLoadError: "providers",
  credentialsEmptyTitle: "No providers yet",
  credentialsEmptyDescription: "Add a provider to give agents a model to run on.",
  credentialsNameLabel: "Name",
  credentialsTypeLabel: "Type",
  credentialsStatusLabel: "Status",
  credentialsCreateAction: "Add provider",
  credentialsCreateDialogTitle: "Add a provider",
  credentialsCreateDialogDescription: "Choose where your models come from.",
  credentialsCreateError: "Couldn't connect that provider — try again.",
  credentialsDeleteAction: "Remove",
  credentialsDeleteConfirm: "Remove this provider?",
  credentialsDeleteError: "Couldn't remove that provider — try again.",
  credentialsEditAction: "Edit",
  credentialsSignInAgainAction: "Sign in again",
  credentialsSignInAgainPending: "Waiting for sign-in…",
  credentialsSignInAgainError: "Couldn't start that sign-in — try again.",
  credentialsEditDialogTitle: "Edit credential",
  credentialsEditDialogDescription:
    "Base URL and model apply to a local, Ollama-style credential; leave them blank otherwise.",
  credentialsModelChangeNotice: "Changing the model restarts your worker onto it.",
  credentialsBaseUrlLabel: "Base URL",
  credentialsModelLabel: "Model",
  credentialsEditSubmit: "Save",
  credentialsEditCancel: "Cancel",
  credentialsEditError: "Couldn't update that credential — try again.",

  auditSectionTitle: "Audit",
  auditSectionDescription: "Who changed what, when — orientation only.",
  auditWhen: "When",
  auditAction: "Action",
  auditActor: "Actor",
  auditTarget: "Target",
  auditEmpty: "No recent changes to show yet.",
  auditHonestyNote:
    "Current-state view, not an append-only audit log — treat as orientation, not evidence.",

  modelsSectionTitle: "Models",
  modelsSectionDescription: "Providers and model offerings resolved for this workbench.",
  modelsLoadError: "this workbench's model catalog",
  modelsEmptyTitle: "No models available",
  modelsEmptyDescription: "No provider has offered a model to this workbench yet.",
  modelsProvidersEmptyTitle: "No providers yet",
  modelsProvidersEmptyDescription: "No credential providers are configured on this workbench.",
  modelsProvidersHeading: "Providers",
  modelsCatalogHeading: "Model offerings",
  modelsProviderColumn: "Provider",
  modelsModelColumn: "Model",
  modelsOfferingsColumn: "Offered by",
  modelsDefaultBadge: "Default",
} as const;
