export {
  WALTER_AGENT_ID,
  WALTER_AGENT_HANDLE,
  WALTER_AGENT_DISPLAY_NAME,
  WALTER_AGENT_DESCRIPTION,
  WALTER_TOOL_PACKAGE_PINS,
  WALTER_SYSTEM_PROMPT,
  WALTER_AGENT_DEFINITION,
  type WalterAgentDefinition,
} from "./definition";
