// Package-owned migrations for @corbits/webhook-triggers's one
// product table. The platform's own schema is authored and applied by
// @intx/db (see scripts/db-setup.ts); this module is the package's
// half of the install story — mount + migrations is the entire
// install story, mirroring `@corbits/chat`'s `migrations.ts`.
// Bookkeeping is deliberately its own table, never the platform's
// drizzle journal, so this package's migration history stays
// extractable on its own.
import postgres from "postgres";

export interface WebhookTriggersMigration {
  name: string;
  sql: string;
}

/**
 * Ordered, explicit migration set for the table declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by
 * drizzle at apply-time) so the applied statements are exactly what
 * is reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const webhookTriggersMigrations: readonly WebhookTriggersMigration[] = [
  {
    name: "0001_webhook_trigger",
    sql: `
      CREATE TABLE IF NOT EXISTS "webhook_triggers"."webhook_trigger" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "name" text NOT NULL,
        "workflow_definition_id" text NOT NULL,
        "input_template" text NOT NULL,
        "secret" text NOT NULL,
        "enabled" boolean NOT NULL DEFAULT true,
        "created_by" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "last_fired_at" timestamptz
      );
    `,
  },
  {
    name: "0002_webhook_trigger_tenant_index",
    sql: `
      CREATE INDEX IF NOT EXISTS "webhook_trigger_tenant_id_idx"
        ON "webhook_triggers"."webhook_trigger" ("tenant_id");
    `,
  },
  {
    name: "0003_move_tables_to_webhook_triggers_schema",
    sql: `
      DO $$
      BEGIN
        IF to_regclass('public.webhook_trigger') IS NOT NULL
           AND to_regclass('webhook_triggers.webhook_trigger') IS NULL THEN
          ALTER TABLE public.webhook_trigger SET SCHEMA webhook_triggers;
        END IF;
      END $$;
    `,
  },
];

// Bookkeeping table for this package's own migrations. Named
// distinctly from the platform's setup ledger and from any drizzle
// journal, so extracting `@corbits/webhook-triggers` out of this repo
// never has to disentangle its history from the platform's. Lives in
// the package's own `webhook_triggers` schema, like the table it owns.
const SCHEMA = "webhook_triggers";
const LEDGER_TABLE = "webhook_triggers_migrations";

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function quoteQualified(schema: string, name: string): string {
  return `${quoteIdentifier(schema)}.${quoteIdentifier(name)}`;
}

export interface ApplyWebhookTriggersMigrationsReport {
  applied: string[];
  alreadyApplied: string[];
}

/**
 * Apply `webhookTriggersMigrations` against `databaseUrl`,
 * idempotently: a migration already recorded in the ledger is
 * skipped, never re-run. Failures are loud — the migration name and
 * the underlying error are both surfaced, since a partial apply here
 * would otherwise fail silently at the next `workbench setup`.
 */
export async function applyWebhookTriggersMigrations(
  databaseUrl: string,
): Promise<ApplyWebhookTriggersMigrationsReport> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await sql.unsafe(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(SCHEMA)}`);

    // Pre-existing dev DBs from before this package had its own schema
    // carry the ledger in `public` — move it in place so its history
    // (which migrations already ran) comes with it. A fresh install
    // never has a `public` ledger, so this is a no-op there.
    await sql.unsafe(
      `DO $$ BEGIN IF to_regclass('public.${LEDGER_TABLE}') IS NOT NULL ` +
        `AND to_regclass('${SCHEMA}.${LEDGER_TABLE}') IS NULL THEN ` +
        `ALTER TABLE "public".${quoteIdentifier(LEDGER_TABLE)} SET SCHEMA ${quoteIdentifier(SCHEMA)}; ` +
        `END IF; END $$;`,
    );

    await sql.unsafe(
      `CREATE TABLE IF NOT EXISTS ${quoteQualified(SCHEMA, LEDGER_TABLE)} (` +
        `name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
    );
    const rows = await sql.unsafe(
      `SELECT name FROM ${quoteQualified(SCHEMA, LEDGER_TABLE)}`,
    );
    const alreadyApplied = new Set(rows.map((row) => String(row["name"])));
    const applied: string[] = [];
    for (const migration of webhookTriggersMigrations) {
      if (alreadyApplied.has(migration.name)) continue;
      try {
        await sql.begin(async (tx) => {
          await tx.unsafe(migration.sql);
          await tx.unsafe(
            `INSERT INTO ${quoteQualified(SCHEMA, LEDGER_TABLE)} (name) VALUES ($1)`,
            [migration.name],
          );
        });
        applied.push(migration.name);
      } catch (error) {
        throw new Error(
          `@corbits/webhook-triggers migration ${JSON.stringify(migration.name)} failed: ` +
            `${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
    }
    return { applied, alreadyApplied: [...alreadyApplied] };
  } finally {
    await sql.end();
  }
}
