// Package-owned migrations for @corbits/webhook-triggers's one
// product table. The platform's own schema is authored and applied by
// @intx/db (see scripts/db-setup.ts); this module is the package's
// half of the install story — mount + migrations is the entire
// install story, mirroring `@corbits/chat`'s `migrations.ts`.
// Bookkeeping is deliberately its own table, never the platform's
// drizzle journal, so this package's migration history stays
// extractable on its own. Mechanics (schema/ledger bootstrap,
// transactional apply, the advisory lock across concurrent hub
// replicas) live in @corbits/migration-runner — this file owns only
// the domain SQL.
import {
  applyPackageMigrations,
  type ApplyPackageMigrationsReport,
  type PackageMigration,
} from "@corbits/migration-runner";

export type WebhookTriggersMigration = PackageMigration;

/**
 * Ordered, explicit migration set for the table declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by
 * drizzle at apply-time) so the applied statements are exactly what
 * is reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const webhookTriggersMigrations: readonly WebhookTriggersMigration[] = [
  {
    name: "0001_webhook_trigger",
    sql: `
      CREATE TABLE IF NOT EXISTS "webhook_triggers"."webhook_trigger" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "name" text NOT NULL,
        "workflow_definition_id" text NOT NULL,
        "input_template" text NOT NULL,
        "secret" text NOT NULL,
        "enabled" boolean NOT NULL DEFAULT true,
        "created_by" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "last_fired_at" timestamptz
      );
    `,
  },
  {
    name: "0002_webhook_trigger_tenant_index",
    sql: `
      CREATE INDEX IF NOT EXISTS "webhook_trigger_tenant_id_idx"
        ON "webhook_triggers"."webhook_trigger" ("tenant_id");
    `,
  },
];

// Named distinctly from the platform's setup ledger and from any
// drizzle journal, so extracting `@corbits/webhook-triggers` out of
// this repo never has to disentangle its history from the platform's.
// Lives in the package's own `webhook_triggers` schema, like the
// table it owns.
const SCHEMA = "webhook_triggers";
const LEDGER_TABLE = "webhook_triggers_migrations";

export type ApplyWebhookTriggersMigrationsReport = ApplyPackageMigrationsReport;

/**
 * Apply `webhookTriggersMigrations` against `databaseUrl`,
 * idempotently: a migration already recorded in the ledger is
 * skipped, never re-run. Failures are loud — the migration name and
 * the underlying error are both surfaced, since a partial apply here
 * would otherwise fail silently at the next `workbench setup`.
 */
export async function applyWebhookTriggersMigrations(
  databaseUrl: string,
): Promise<ApplyWebhookTriggersMigrationsReport> {
  return applyPackageMigrations({
    databaseUrl,
    schema: SCHEMA,
    ledgerTable: LEDGER_TABLE,
    migrations: webhookTriggersMigrations,
    packageLabel: "@corbits/webhook-triggers",
  });
}
