// Package-owned migrations for @corbits/webhook-triggers's one
// product table. The platform's own schema is authored and applied by
// @intx/db (see scripts/db-setup.ts); this module is the package's
// half of the install story — mount + migrations is the entire
// install story, mirroring `@corbits/chat`'s `migrations.ts`.
// Bookkeeping is deliberately its own table, never the platform's
// drizzle journal, so this package's migration history stays
// extractable on its own. Mechanics (schema/ledger bootstrap,
// transactional apply, the advisory lock across concurrent hub
// replicas) live in @corbits/migration-runner — this file owns only
// the domain SQL.
import {
  applyPackageMigrations,
  type ApplyPackageMigrationsReport,
  type PackageMigration,
} from "@corbits/migration-runner";

export type WebhookTriggersMigration = PackageMigration;

/**
 * Ordered, explicit migration set for the table declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by
 * drizzle at apply-time) so the applied statements are exactly what
 * is reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const webhookTriggersMigrations: readonly WebhookTriggersMigration[] = [
  {
    name: "0001_webhook_trigger",
    sql: `
      CREATE TABLE IF NOT EXISTS "webhook_triggers"."webhook_trigger" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "name" text NOT NULL,
        "workflow_definition_id" text NOT NULL,
        "input_template" text NOT NULL,
        "secret" text NOT NULL,
        "enabled" boolean NOT NULL DEFAULT true,
        "created_by" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "last_fired_at" timestamptz
      );
    `,
  },
  {
    name: "0002_webhook_trigger_tenant_index",
    sql: `
      CREATE INDEX IF NOT EXISTS "webhook_trigger_tenant_id_idx"
        ON "webhook_triggers"."webhook_trigger" ("tenant_id");
    `,
  },
  {
    // CL-7242: startReviewingRepos's check-then-act (hasWebhookTrigger
    // then createWebhookTrigger) reads (tenant_id, workflow_definition_id,
    // name) with no atomic backstop, so two concurrent "start reviewing"
    // calls for the same repo can both read "no trigger yet" and both
    // insert -- two live triggers with the same name but different
    // secrets. Reconcile first: a database already carrying the race's
    // duplicates would otherwise fail CREATE UNIQUE INDEX. Keep the
    // oldest row per tuple and delete the rest. This whole migration
    // runs inside one transaction (applyWebhookTriggersMigrations wraps
    // each entry in `sql.begin`), so the delete and the index build
    // can't be split by a concurrent writer.
    name: "0003_webhook_trigger_tenant_definition_name_unique",
    sql: `
      DELETE FROM "webhook_triggers"."webhook_trigger" AS t
      USING "webhook_triggers"."webhook_trigger" AS older
      WHERE t.tenant_id = older.tenant_id
        AND t.workflow_definition_id = older.workflow_definition_id
        AND t.name = older.name
        AND (older.created_at, older.id) < (t.created_at, t.id);

      CREATE UNIQUE INDEX IF NOT EXISTS "webhook_trigger_tenant_definition_name_unique"
        ON "webhook_triggers"."webhook_trigger" ("tenant_id", "workflow_definition_id", "name");
    `,
  },
  {
    // CL-7242: the paired fix to 0003, in our own schema rather than
    // Interchange's. `startReviewingRepos` acquires a short-lived
    // lease on `(tenant_id, repo)` before its check-then-act body
    // (hasRepoGrant/mintRepoGrant, hasWebhookTrigger/createWebhookTrigger)
    // runs, so two concurrent calls for the same repo can never both
    // enter that body -- only one can hold the lease at a time. The
    // unique index must exist before any `ON CONFLICT (tenant_id, repo)`
    // is issued against this table at runtime (Postgres requires a
    // matching unique constraint/index for that clause, or the insert
    // errors), so both land in this one migration, index second.
    name: "0004_repo_review_lease",
    sql: `
      CREATE TABLE IF NOT EXISTS "webhook_triggers"."repo_review_lease" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "repo" text NOT NULL,
        "leased_at" timestamptz NOT NULL DEFAULT now()
      );

      CREATE UNIQUE INDEX IF NOT EXISTS "repo_review_lease_tenant_repo_unique"
        ON "webhook_triggers"."repo_review_lease" ("tenant_id", "repo");
    `,
  },
];

// Named distinctly from the platform's setup ledger and from any
// drizzle journal, so extracting `@corbits/webhook-triggers` out of
// this repo never has to disentangle its history from the platform's.
// Lives in the package's own `webhook_triggers` schema, like the
// table it owns.
const SCHEMA = "webhook_triggers";
const LEDGER_TABLE = "webhook_triggers_migrations";

export type ApplyWebhookTriggersMigrationsReport = ApplyPackageMigrationsReport;

/**
 * Apply `webhookTriggersMigrations` against `databaseUrl`,
 * idempotently: a migration already recorded in the ledger is
 * skipped, never re-run. Failures are loud — the migration name and
 * the underlying error are both surfaced, since a partial apply here
 * would otherwise fail silently at the next `workbench setup`.
 */
export async function applyWebhookTriggersMigrations(
  databaseUrl: string,
): Promise<ApplyWebhookTriggersMigrationsReport> {
  return applyPackageMigrations({
    databaseUrl,
    schema: SCHEMA,
    ledgerTable: LEDGER_TABLE,
    migrations: webhookTriggersMigrations,
    packageLabel: "@corbits/webhook-triggers",
  });
}
