// Every user-facing word the settings surface prints, in one place. Nothing
// in the settings-ui/* components inlines its own copy; it imports from here.

export const SETTINGS_STRINGS = {
  pageTitle: "Settings",
  pageSubtitle: "Personal settings and settings shared across your workbench",
  sectionsNavLabel: "Settings sections",
  emptySectionsTitle: "Nothing to show",
  emptySectionsDescription: "No settings sections are available right now.",
  groupAccountLabel: "Personal Settings",
  groupEveryoneLabel: "Shared Settings",
  advancedSectionsSummary: "Advanced",
  advancedSectionsHint: "Roles, granular permissions, and activity history.",

  agentSectionTitle: "Your agent",
  agentSectionDescription:
    "How your default agent works for you on this workbench.",
  agentAutonomyHeading: "Autonomy",
  agentAutonomyLabel: "Default behavior",
  agentAutonomyPrepare: "Prepare only — draft, never send",
  agentAutonomyGated: "Execute with gates — ask before side effects",
  agentAutonomyAutonomous: "Autonomous in approved spaces",
  agentBriefLabel: "Morning brief",
  agentBriefOff: "Off",
  agentBrief0730: "07:30 local",
  agentBrief0900: "09:00 local",
  agentInstructionsHeading: "Standing instructions",
  agentInstructionsLabel: "Applied to every chat",
  agentInstructionsDefault:
    "Concise, multiplayer-aware. Prefer canvas for artifacts. End turns with a clear next step.",
  agentPinnedHeading: "Pinned skills",
  agentPinnedHint:
    "Pinning edits the skill library when that store is wired; chips here are draft-only for now.",
  agentInferenceHeading: "Inference",
  agentCreativityLabel: "Creativity",
  agentThinkingLabel: "Thinking budget",
  agentSaveAction: "Save",
  agentSaveHonesty:
    "Draft only — personal agent prefs are not stored on the hub yet.",

  notificationsSectionTitle: "Notifications",
  notificationsSectionDescription: "How activity reaches you.",
  notificationsMentions: "Mentions & DMs",
  notificationsApprovals: "Approvals",
  notificationsRoutineFail: "Failed deliveries",
  notificationsSaveAction: "Save",
  notificationsSaveHonesty:
    "Draft only — per-user notification prefs are not stored on the hub yet.",

  settingsSavedToast: "Settings saved",

  benchNoneSelectedTitle: "No workbench selected",
  benchNoneSelectedDescription: "Choose a workbench from the switcher first.",

  accountSectionTitle: "General",
  accountSectionDescription: "How the hub identifies you.",
  accountNameLabel: "Name",
  accountEmailLabel: "Email",
  accountLoadError: "your account",
  accountReadOnlyNote:
    "Managed through the authentication API; editing from this screen has not been built yet.",
  accountSignOutAction: "Sign out",
  accountDetailsHeading: "Account details",
  accountCopyEmailAction: "Copy email",
  accountEmailCopiedToast: "Copied",
  accountEmailCopyError: "Couldn't copy the email",

  appearanceSectionTitle: "Appearance",
  appearanceThemeLabel: "Theme",
  themeFollowSystem: "Follow System",
  themeLight: "Light",
  themeDark: "Dark",

  generalAgentGroupTitle: "Agent",
  agentTimezoneLabel: "Timezone",
  agentTimezoneAutoDetect: (timezone: string) => `Auto-detect (${timezone})`,

  peopleSectionTitle: "People",
  peopleSectionDescription: "Everyone with a seat on this workbench.",
  peopleLoadError: "this workbench's people",
  peopleEmptyTitle: "No people yet",
  peopleEmptyDescription: "Invite someone to get this workbench started.",
  peopleInviteAction: "Invite someone",
  peopleInviteDialogTitle: "Invite someone",
  peopleInviteDialogDescription:
    "They'll get access when they sign up with this email.",
  peopleInviteEmailLabel: "Email",
  peopleInviteEmailPlaceholder: "person@example.com",
  peopleInviteRoleLabel: "Role",
  peopleInviteRoleOwner: "Owner",
  peopleInviteRoleMember: "Member",
  peopleInviteSubmit: "Invite",
  peopleInviteInviting: "Inviting…",
  peopleInviteCancel: "Cancel",
  peopleInviteError: "Couldn't send that invite — try again.",
  peopleSuspend: "Suspend",
  peopleReactivate: "Reactivate",
  peopleRemove: "Remove",
  peopleRemoveConfirm: "Remove for good?",
  peopleStatusUpdateError: "Couldn't update that person's status — try again.",
  peopleRemoveError: "Couldn't remove that person — try again.",
  peopleUnnamedAgent: "Unnamed agent",
  peopleRoleNone: "none",
  peopleKindUser: "user",
  peopleKindAgent: "agent",
  peopleKindWorkflow: "workflow",
  peopleRoleChangeError: "Couldn't change that person's role — try again.",
  peopleLastOwnerError:
    "This workbench needs at least one owner — make someone else an owner first.",

  pendingInvitesTitle: "Pending invites",
  pendingInvitesDescription: "Invited, but not signed up yet.",
  pendingInvitesEmpty: "No pending invites.",
  pendingInvitesLoadError: "pending invites",
  pendingInviteCancel: "Cancel",
  pendingInviteCancelConfirm: "Cancel this invite?",
  pendingInviteCancelError: "Couldn't cancel that invite — try again.",

  accessPolicyHeading: "Who can join",
  accessPolicyLoadError: "who can join",
  accessPolicySignupLabel: "Self-signup",
  accessPolicySignupOff: "Off — invites only (default)",
  accessPolicySignupAllowedDomains: "Anyone with an allowed email domain",
  accessPolicySignupOpenOption: "Anyone with an account",
  accessPolicyDomainsLabel: "Allowed email domains",
  accessPolicyDomainsPlaceholder: "acme.example",
  accessPolicyDomainsAdd: "Add",
  accessPolicyDomainsEmptyHint:
    "No domains added yet — with self-signup on and no domains listed, any email domain is allowed.",
  accessPolicyDomainsRemove: "Remove",
  accessPolicySubCreationLabel: "Who can create a sub-workbench here",
  accessPolicySubCreationOwners: "Owners only (default)",
  accessPolicySubCreationOwnersAdmins: "Owners and admins",
  accessPolicySubCreationNone: "Nobody",
  accessPolicySaveAction: "Save",
  accessPolicySaving: "Saving…",
  accessPolicySaveError: "Couldn't save that change — try again.",
  accessPolicyNote:
    "Closed by default: no open signup, no self-serve sub-workbenches. These settings apply to this workbench.",
  accessPolicyEnvOverrideNotice:
    "The operator has sign-up switched off at the server level, so people still can't create an account yet — even though this setting would otherwise allow it. Ask whoever manages this deployment to enable self-signup.",

  rolesSectionTitle: "Roles",
  rolesSectionDescription:
    "This workbench's roles and who they're assigned to.",
  rolesLoadError: "this workbench's roles",
  rolesEmptyTitle: "No roles yet",
  rolesEmptyDescription: "Create a custom role to get started.",
  rolesCreateAction: "New role",
  rolesCreateDialogTitle: "New role",
  rolesCreateDialogDescription:
    "Custom roles start with no grants of their own.",
  rolesNameLabel: "Name",
  rolesNamePlaceholder: "e.g. Billing",
  rolesDescriptionLabel: "Description",
  rolesCreateSubmit: "Create",
  rolesCreateCancel: "Cancel",
  rolesCreateError: "Couldn't create that role — try again.",
  rolesRenameError: "Couldn't rename that role — try again.",
  rolesDeleteError:
    "Couldn't delete that role — it may still be assigned to someone.",
  rolesSystemBadge: "system",
  rolesSystemImmutableNote: "System roles can't be renamed or deleted.",
  rolesRenameAction: "Rename",
  rolesRenameSave: "Save",
  rolesRenameCancel: "Cancel",
  rolesDeleteAction: "Delete",
  rolesDeleteConfirm: "Delete for good?",
  rolesAssignSectionTitle: "Assign a role",
  rolesAssignPersonLabel: "Person",
  rolesAssignRoleLabel: "Role",
  rolesAssignSubmit: "Assign",
  rolesAssignError: "Couldn't assign that role — try again.",
  rolesUnassignError: "Couldn't remove that role — try again.",
  rolesAssignmentsTitle: "Assignments",
  rolesAssignmentsEmpty: "No one has been assigned a role yet.",
  rolesUnassign: "Remove",

  grantsSectionTitle: "What agents can do",
  grantsSectionDescription:
    "What each role or person is allowed, denied, or asked about, and on what.",
  grantsLoadError: "this workbench's rules",
  grantsEmptyTitle: "No rules match these filters",
  grantsEmptyDescription: "Try clearing a filter, or create a new rule.",
  grantsCreateAction: "New rule",
  grantsCreateDialogTitle: "New rule",
  grantsCreateDialogDescription:
    "Set exactly one role or one person a resource and action.",
  grantsTargetTypeLabel: "Applies to",
  grantsTargetTypeRole: "A role",
  grantsTargetTypeRoleDescription: "Everyone assigned this role.",
  grantsTargetTypePrincipal: "A person, agent, or workflow",
  grantsTargetTypePrincipalDescription:
    "One specific account — human or machine.",
  grantsTargetLabel: "Target",
  grantsResourceLabel: "Resource",
  grantsActionLabel: "Action",
  grantsEffectLabel: "Effect",
  grantsOriginLabel: "Origin",
  grantsExpiresLabel: "Expires",
  grantsCreateSubmit: "Create",
  grantsCreateCancel: "Cancel",
  grantsCreateError: "Couldn't create that rule — try again.",
  grantsRevoke: "Revoke",
  grantsRevokeConfirm: "Revoke for good?",
  grantsRevokeError: "Couldn't revoke that rule — try again.",
  grantsFilterPrincipal: "Person",
  grantsFilterRole: "Role",
  grantsFilterResource: "Resource",
  grantsFilterEffect: "Effect",
  grantsFilterAny: "Any",
  grantsNoExpiry: "Never",
  grantCreatedToast: "Rule created",
  grantRevokedToast: "Rule revoked",

  credentialsSectionTitle: "Keys",
  credentialsSectionDescription:
    "API keys and tokens this workbench stores for providers. Secrets are write-only — they are never shown again after create.",
  credentialsLoadError: "this workbench's keys",
  credentialsEmptyTitle: "No keys yet",
  credentialsEmptyDescription:
    "Add a key so your agents can reach this service.",
  credentialsCreateAction: "New key",
  credentialsCreateDialogTitle: "New key",
  credentialsCreateDialogDescription:
    "Store a secret against a provider. The secret is encrypted and never returned on later reads.",
  credentialsProviderLabel: "Provider",
  credentialsNoProviders: "No providers configured yet",
  credentialsNameLabel: "Name",
  credentialsNamePlaceholder: "e.g. OpenAI production",
  credentialsTypeLabel: "Type",
  credentialsSecretLabel: "Secret",
  credentialsDescriptionLabel: "Description (optional)",
  credentialsCreateSubmit: "Store",
  credentialsCreateSubmitting: "Storing…",
  credentialsCreateCancel: "Cancel",
  credentialsCreateError: "Couldn't store that key — try again.",
  credentialsDelete: "Revoke",
  credentialsDeleting: "Revoking…",
  credentialsDeleteConfirm: "Revoke for good?",
  credentialsDeleteError: "Couldn't revoke that key — try again.",
  credentialsRemovedProvider: "Removed provider",
  credentialSavedToast: "Key saved · value hidden",
  credentialRevokedToast: "Key revoked",

  connectionsSectionTitle: "AI providers",
  connectionsSectionDescription:
    "Choose the model route Myra and new workbenches use, then connect the providers behind it.",
  connectionsLoadError: "connections",
  connectionsStatusNotConnected: "Not connected",
  connectionsStatusConnected: "Connected",
  connectionsStatusNeedsAttention: "Needs attention",
  connectionsStatusNotConfigured: "Needs setup",
  connectionsNotConfiguredHint:
    "An operator needs to register an OAuth app for this connector before anyone can connect it.",
  connectionsConnectAction: "Connect",
  connectionsReconnectAction: "Reconnect",
  connectionsDisconnectAction: "Disconnect",
  connectionsDisconnectConfirm: "Disconnect for good?",
  connectionsDisconnectError: "Couldn't disconnect — try again.",
  connectionsDefaultModelLine: (model: string) => `Default model: ${model}`,
  connectionsDefaultModelLabel: "Default model:",
  connectionsSetDefaultModelError:
    "Couldn't set the default model — try again.",
  connectionsPinnedByPrefix: "Used by workflows: ",
  connectionsPinnedByNone: "Available to any workflow",
  connectionsPinnedByApproximationNote:
    "Based on each workflow's declared tool-package pins, not a live query against deployed definitions — may lag a workflow's actual tool usage.",
  connectionsDialogConnectTitle: (name: string) => `Connect ${name}`,
  connectionsDialogReconnectTitle: (name: string) => `Reconnect ${name}`,
  connectionsDialogDescription:
    "Sealed on save — this key is never shown again after create. A bad key never gets saved; connecting surfaces the problem right here.",
  connectionsKeyLabel: "API key",
  connectionsConnectDialogAction: "Connect",
  connectionsConnecting: "Connecting…",
  connectionsSaving: "Saving…",
  connectionsCancel: "Cancel",
  connectionsConnectedToast: (name: string) => `${name} connected`,
  connectionsAdvancedSummary:
    "All credentials — including certificates and other types",
  connectionsWebhookLoadError: "Couldn't load the Granola webhook",
  connectionsWebhookNotSetUp: "Not set up",
  connectionsWebhookSetUpAction: "Set up",
  connectionsWebhookManageAction: "Manage",
  connectionsWebhookTriggerCount: (count: number) =>
    `${count} webhook${count === 1 ? "" : "s"} wired`,
  connectionsWebhookLastDelivery: (when: string) => `Last delivery ${when}`,
  connectionsWebhookNoDeliveries: "No deliveries yet",
  connectionsWebhookDirectionNote:
    "Workbench gives you a signed webhook address Granola calls.",
  connectionsWebhookDialogTitle: "Granola inbound webhook",
  connectionsWebhookDialogDescription:
    "This address is yours to give to Granola — nothing to paste from Granola's side. The signing secret proves a delivery really came from Granola; it's shown once, right after you create or rotate it.",
  connectionsWebhookHookUrlLabel: "Hook URL",
  connectionsWebhookCopyHookUrl: "Copy hook URL",
  connectionsWebhookSigningSecretLabel: "Signing secret",
  connectionsWebhookCopySigningSecret: "Copy signing secret",
  connectionsWebhookNoRoutine:
    "No Granola call-notes routine yet. Create one from Routines, then come back here to wire its inbound webhook.",
  connectionsWebhookCreateAction: "Create",
  connectionsWebhookRotateAction: "Rotate secret",
  connectionsWebhookRotating: "Rotating…",
  connectionsWebhookHiddenSecretNote:
    "Hidden — shown only once, right after creation or a rotate. Rotate to issue (and reveal) a new one; the old secret stops verifying immediately.",

  auditSectionTitle: "Audit",
  auditSectionDescription: "Who changed what, when — orientation only.",
  auditWhen: "When",
  auditAction: "Action",
  auditActor: "Actor",
  auditTarget: "Target",
  auditEmpty: "No recent changes to show yet.",
  auditHonestyNote:
    "Current-state view, not an append-only audit log — treat as orientation, not evidence.",
} as const;
