// Package-owned migrations for @corbits/slack-tag's one product table.
// The platform's own schema is authored and applied by @intx/db (see
// scripts/db-setup.ts); this module is the package's half of the
// install story — mount + migrations is the entire install story,
// mirroring `@corbits/webhook-triggers`'s `migrations.ts`. Bookkeeping
// is deliberately its own table, never the platform's drizzle journal,
// so this package's migration history stays extractable on its own.
import postgres from "postgres";

export interface SlackTagMigration {
  name: string;
  sql: string;
}

/**
 * Ordered, explicit migration set for the table declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by drizzle
 * at apply-time) so the applied statements are exactly what is
 * reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const slackTagMigrations: readonly SlackTagMigration[] = [
  {
    name: "0001_slack_channel_binding",
    sql: `
      CREATE TABLE IF NOT EXISTS "slack_tag"."slack_channel_binding" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "slack_channel_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "slack_channel_binding_tenant_channel_key"
          UNIQUE ("tenant_id", "slack_channel_id")
      );
    `,
  },
];

// Bookkeeping table for this package's own migrations. Named
// distinctly from the platform's setup ledger and from any drizzle
// journal, so extracting `@corbits/slack-tag` out of this repo never
// has to disentangle its history from the platform's. Lives in the
// package's own `slack_tag` schema, like the table it owns.
const SCHEMA = "slack_tag";
const LEDGER_TABLE = "slack_tag_migrations";

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function quoteQualified(schema: string, name: string): string {
  return `${quoteIdentifier(schema)}.${quoteIdentifier(name)}`;
}

export interface ApplySlackTagMigrationsReport {
  applied: string[];
  alreadyApplied: string[];
}

/**
 * Apply `slackTagMigrations` against `databaseUrl`, idempotently: a
 * migration already recorded in the ledger is skipped, never re-run.
 * Failures are loud — the migration name and the underlying error are
 * both surfaced, since a partial apply here would otherwise fail
 * silently at the next `workbench setup`.
 */
export async function applySlackTagMigrations(
  databaseUrl: string,
): Promise<ApplySlackTagMigrationsReport> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await sql.unsafe(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(SCHEMA)}`);

    await sql.unsafe(
      `CREATE TABLE IF NOT EXISTS ${quoteQualified(SCHEMA, LEDGER_TABLE)} (` +
        `name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
    );
    const rows = await sql.unsafe(
      `SELECT name FROM ${quoteQualified(SCHEMA, LEDGER_TABLE)}`,
    );
    const alreadyApplied = new Set(rows.map((row) => String(row["name"])));
    const applied: string[] = [];
    for (const migration of slackTagMigrations) {
      if (alreadyApplied.has(migration.name)) continue;
      try {
        await sql.begin(async (tx) => {
          await tx.unsafe(migration.sql);
          await tx.unsafe(
            `INSERT INTO ${quoteQualified(SCHEMA, LEDGER_TABLE)} (name) VALUES ($1)`,
            [migration.name],
          );
        });
        applied.push(migration.name);
      } catch (error) {
        throw new Error(
          `@corbits/slack-tag migration ${JSON.stringify(migration.name)} failed: ` +
            `${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
    }
    return { applied, alreadyApplied: [...alreadyApplied] };
  } finally {
    await sql.end();
  }
}
