[build]
builder = "dockerfile"
dockerfilePath = "apps/admin-ui/Dockerfile"
watchPatterns = ["apps/admin-ui/**", "interchange"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
