// Package-owned migrations for @corbits/chat's two product tables.
// The platform's own schema is authored and applied by @intx/db (see
// scripts/db-setup.ts); this module is the package's half of the
// install story described by the signed structure doc: "mount +
// migrations is the entire install story." Bookkeeping is deliberately
// its own table, never the platform's drizzle journal, so the chat
// package's migration history stays extractable on its own.
import postgres from "postgres";

export interface ChatMigration {
  name: string;
  sql: string;
}

/**
 * Ordered, explicit migration set for the two tables declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by drizzle
 * at apply-time) so the applied statements are exactly what is
 * reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const chatMigrations: readonly ChatMigration[] = [
  {
    name: "0001_channel_settings",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_settings" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "settings" jsonb NOT NULL,
        "updated_by" text NOT NULL,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id")
      );
    `,
  },
  {
    name: "0002_channel_read_state",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_read_state" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "last_seen_created_at" timestamptz NOT NULL,
        "last_seen_id" text NOT NULL,
        PRIMARY KEY ("tenant_id", "channel_id", "principal_id")
      );
    `,
  },
  {
    name: "0003_channel_launch",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_launch" (
        "tenant_id" text NOT NULL,
        "instance_id" text NOT NULL,
        "folded_body" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("instance_id")
      );
    `,
  },
  {
    name: "0004_channel_launch_noop_inference",
    sql: `
      ALTER TABLE "chat"."channel_launch"
        ADD COLUMN IF NOT EXISTS "noop_inference" boolean NOT NULL DEFAULT false;
    `,
  },
  {
    name: "0005_channel_tenancy",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_tenancy" (
        "channel_id" text NOT NULL,
        "tenant_id" text NOT NULL,
        "parent_tenant_id" text NOT NULL,
        "slug" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("channel_id"),
        UNIQUE ("tenant_id")
      );
    `,
  },
  {
    name: "0006_channel_tenancy_parent_index",
    sql: `
      CREATE INDEX IF NOT EXISTS "channel_tenancy_parent_tenant_id_idx"
        ON "chat"."channel_tenancy" ("parent_tenant_id");
    `,
  },
  {
    name: "0007_chat_bench_settings",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."chat_bench_settings" (
        "tenant_id" text NOT NULL,
        "settings" jsonb NOT NULL,
        "updated_by" text NOT NULL,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id")
      );
    `,
  },
  // Before this rollout, `channel_settings.settings->>'chat/contextWindow'`
  // had exactly one meaning: an explicit per-channel value, read back by
  // `contextWindowOf` with a code-level fallback of 20 for any row that
  // never set the key at all. There was no bench-wide default for a
  // channel to "inherit" — every existing value already on a row is
  // therefore a real, deliberately-set override, not some default that
  // happened to get written. Introducing bench defaults must not
  // silently reinterpret those rows as "inheriting" (they were never
  // inheriting anything), so this migration leaves every row that
  // already carries the key untouched — it stays an explicit override —
  // and only touches rows with no key at all, making that absence
  // explicit as `null` (inherit) rather than continuing to rely on an
  // implicit, code-only fallback now that a real bench-wide default
  // exists to inherit from.
  {
    name: "0008_channel_context_window_explicit_inherit",
    sql: `
      UPDATE "chat"."channel_settings"
      SET "settings" = jsonb_set("settings", '{chat/contextWindow}', 'null'::jsonb)
      WHERE NOT ("settings" ? 'chat/contextWindow');
    `,
  },
  {
    name: "0009_channel_threads",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_threads" (
        "id" text PRIMARY KEY,
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "kind" text NOT NULL,
        "parent_message_id" text,
        "run_ref" text,
        "title" text,
        "created_at" timestamptz NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS "channel_threads_channel_idx"
        ON "chat"."channel_threads" ("tenant_id", "channel_id");
      CREATE TABLE IF NOT EXISTS "chat"."channel_thread_messages" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "thread_id" text NOT NULL,
        "message_id" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id")
      );
      CREATE INDEX IF NOT EXISTS "channel_thread_messages_thread_idx"
        ON "chat"."channel_thread_messages" ("tenant_id", "thread_id");
    `,
  },
  {
    name: "0010_block_responses",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."block_responses" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "block_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "payload" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id", "block_id", "principal_id")
      );
      CREATE INDEX IF NOT EXISTS "block_responses_block_idx"
        ON "chat"."block_responses" ("tenant_id", "channel_id", "message_id", "block_id");
    `,
  },
  {
    name: "0011_channel_threads_parent_thread_id",
    sql: `
      ALTER TABLE "chat"."channel_threads"
        ADD COLUMN IF NOT EXISTS "parent_thread_id" text;
      CREATE INDEX IF NOT EXISTS "channel_threads_parent_thread_idx"
        ON "chat"."channel_threads" ("tenant_id", "parent_thread_id");
    `,
  },
  {
    name: "0012_message_reactions",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."message_reactions" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "emoji" text NOT NULL,
        "principal_id" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id", "emoji", "principal_id")
      );
      CREATE INDEX IF NOT EXISTS "message_reactions_message_idx"
        ON "chat"."message_reactions" ("tenant_id", "channel_id", "message_id");
    `,
  },
  {
    name: "0013_pinned_messages",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."pinned_messages" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "message_id" text NOT NULL,
        "pinned_by" text NOT NULL,
        "pinned_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id", "message_id")
      );
      CREATE INDEX IF NOT EXISTS "pinned_messages_channel_idx"
        ON "chat"."pinned_messages" ("tenant_id", "channel_id");
    `,
  },
  {
    name: "0014_channel_share",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_share" (
        "owning_tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "projected_tenant_id" text NOT NULL,
        "created_by" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("channel_id", "projected_tenant_id")
      );
      CREATE INDEX IF NOT EXISTS "channel_share_projected_idx"
        ON "chat"."channel_share" ("projected_tenant_id");
    `,
  },
  {
    name: "0015_channel_share_member",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."channel_share_member" (
        "projected_tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "added_by" text NOT NULL,
        "added_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("projected_tenant_id", "channel_id", "principal_id")
      );
    `,
  },
  {
    name: "0016_finalized_turn_write_claim",
    sql: `
      CREATE TABLE IF NOT EXISTS "chat"."finalized_turn_write_claim" (
        "tenant_id" text NOT NULL,
        "surface" text NOT NULL,
        "claim_key" text NOT NULL,
        "claimed_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "surface", "claim_key")
      );
    `,
  },
];

/**
 * Every folded run this package's own launches recorded in
 * `channel_launch` — one row per channel host or invited agent (see
 * `channel_launch`'s own doc comment in `./schema.ts`). Exists for
 * `@corbits/folded-runs`' one-time backfill (CL-6061): before its own
 * `folded_run` marker table existed, this table was the only durable
 * record that a given run was folded. This package never writes to
 * `folded_runs.folded_run` itself — that would make it depend on a
 * package that already depends on it — so it only ever reads its own
 * schema and hands the ids back; the caller (scripts/db-setup.ts, the
 * one place that already knows every installed package) is the one
 * that inserts them as markers via `@corbits/folded-runs`' own export.
 */
export interface ChannelLaunchFoldedRunSeed {
  readonly id: string;
  readonly tenantId: string;
}

export async function listChannelLaunchFoldedRunIds(
  databaseUrl: string,
): Promise<ChannelLaunchFoldedRunSeed[]> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    const rows = await sql.unsafe(
      `SELECT "instance_id" AS "id", "tenant_id" AS "tenantId" FROM "chat"."channel_launch"`,
    );
    return rows.map((row) => ({
      id: String(row["id"]),
      tenantId: String(row["tenantId"]),
    }));
  } finally {
    await sql.end();
  }
}

// Bookkeeping table for this package's own migrations. Named
// distinctly from the platform's setup ledger (`workbench_setup_migration`,
// in scripts/db-setup.ts) and from any drizzle journal, so extracting
// @corbits/chat out of this repo never has to disentangle its history
// from the platform's. Lives in the package's own `chat` schema, like
// every other table it owns.
const SCHEMA = "chat";
const LEDGER_TABLE = "chat_migrations";

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function quoteQualified(schema: string, name: string): string {
  return `${quoteIdentifier(schema)}.${quoteIdentifier(name)}`;
}

export interface ApplyChatMigrationsReport {
  applied: string[];
  alreadyApplied: string[];
}

/**
 * Apply `chatMigrations` against `databaseUrl`, idempotently: a
 * migration already recorded in the ledger is skipped, never re-run.
 * Failures are loud — the migration name and the underlying error are
 * both surfaced, since a partial apply here would otherwise fail
 * silently at the next `workbench setup`.
 */
export async function applyChatMigrations(
  databaseUrl: string,
): Promise<ApplyChatMigrationsReport> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await sql.unsafe(`CREATE SCHEMA IF NOT EXISTS ${quoteIdentifier(SCHEMA)}`);

    await sql.unsafe(
      `CREATE TABLE IF NOT EXISTS ${quoteQualified(SCHEMA, LEDGER_TABLE)} (` +
        `name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
    );
    const rows = await sql.unsafe(
      `SELECT name FROM ${quoteQualified(SCHEMA, LEDGER_TABLE)}`,
    );
    const alreadyApplied = new Set(rows.map((row) => String(row["name"])));
    const applied: string[] = [];
    for (const migration of chatMigrations) {
      if (alreadyApplied.has(migration.name)) continue;
      try {
        await sql.begin(async (tx) => {
          await tx.unsafe(migration.sql);
          await tx.unsafe(
            `INSERT INTO ${quoteQualified(SCHEMA, LEDGER_TABLE)} (name) VALUES ($1)`,
            [migration.name],
          );
        });
        applied.push(migration.name);
      } catch (error) {
        throw new Error(
          `@corbits/chat migration ${JSON.stringify(migration.name)} failed: ` +
            `${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
    }
    return { applied, alreadyApplied: [...alreadyApplied] };
  } finally {
    await sql.end();
  }
}
