// Package-owned migrations for @corbits/chat's two product tables.
// The platform's own schema is authored and applied by @intx/db (see
// scripts/db-setup.ts); this module is the package's half of the
// install story described by the signed structure doc: "mount +
// migrations is the entire install story." Bookkeeping is deliberately
// its own table, never the platform's drizzle journal, so the chat
// package's migration history stays extractable on its own.
import postgres from "postgres";

export interface ChatMigration {
  name: string;
  sql: string;
}

/**
 * Ordered, explicit migration set for the two tables declared in
 * `./schema.ts`. Kept as literal SQL (rather than generated by drizzle
 * at apply-time) so the applied statements are exactly what is
 * reviewed here — no hidden codegen step between this file and the
 * database.
 */
export const chatMigrations: readonly ChatMigration[] = [
  {
    name: "0001_channel_settings",
    sql: `
      CREATE TABLE IF NOT EXISTS "channel_settings" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "settings" jsonb NOT NULL,
        "updated_by" text NOT NULL,
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("tenant_id", "channel_id")
      );
    `,
  },
  {
    name: "0002_channel_read_state",
    sql: `
      CREATE TABLE IF NOT EXISTS "channel_read_state" (
        "tenant_id" text NOT NULL,
        "channel_id" text NOT NULL,
        "principal_id" text NOT NULL,
        "last_seen_created_at" timestamptz NOT NULL,
        "last_seen_id" text NOT NULL,
        PRIMARY KEY ("tenant_id", "channel_id", "principal_id")
      );
    `,
  },
  {
    name: "0003_channel_launch",
    sql: `
      CREATE TABLE IF NOT EXISTS "channel_launch" (
        "tenant_id" text NOT NULL,
        "instance_id" text NOT NULL,
        "folded_body" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("instance_id")
      );
    `,
  },
  {
    name: "0004_channel_launch_noop_inference",
    sql: `
      ALTER TABLE "channel_launch"
        ADD COLUMN IF NOT EXISTS "noop_inference" boolean NOT NULL DEFAULT false;
    `,
  },
  {
    name: "0005_channel_tenancy",
    sql: `
      CREATE TABLE IF NOT EXISTS "channel_tenancy" (
        "channel_id" text NOT NULL,
        "tenant_id" text NOT NULL,
        "parent_tenant_id" text NOT NULL,
        "slug" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY ("channel_id"),
        UNIQUE ("tenant_id")
      );
    `,
  },
];

// Bookkeeping table for this package's own migrations. Named
// distinctly from the platform's setup ledger (`workbench_setup_migration`,
// in scripts/db-setup.ts) and from any drizzle journal, so extracting
// @corbits/chat out of this repo never has to disentangle its history
// from the platform's.
const LEDGER_TABLE = "chat_migrations";

function quoteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

export interface ApplyChatMigrationsReport {
  applied: string[];
  alreadyApplied: string[];
}

/**
 * Apply `chatMigrations` against `databaseUrl`, idempotently: a
 * migration already recorded in the ledger is skipped, never re-run.
 * Failures are loud — the migration name and the underlying error are
 * both surfaced, since a partial apply here would otherwise fail
 * silently at the next `workbench setup`.
 */
export async function applyChatMigrations(
  databaseUrl: string,
): Promise<ApplyChatMigrationsReport> {
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await sql.unsafe(
      `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(LEDGER_TABLE)} (` +
        `name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
    );
    const rows = await sql.unsafe(
      `SELECT name FROM ${quoteIdentifier(LEDGER_TABLE)}`,
    );
    const alreadyApplied = new Set(rows.map((row) => String(row["name"])));
    const applied: string[] = [];
    for (const migration of chatMigrations) {
      if (alreadyApplied.has(migration.name)) continue;
      try {
        await sql.unsafe(migration.sql);
        await sql.unsafe(
          `INSERT INTO ${quoteIdentifier(LEDGER_TABLE)} (name) VALUES ($1)`,
          [migration.name],
        );
        applied.push(migration.name);
      } catch (error) {
        throw new Error(
          `@corbits/chat migration ${JSON.stringify(migration.name)} failed: ` +
            `${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
    }
    return { applied, alreadyApplied: [...alreadyApplied] };
  } finally {
    await sql.end();
  }
}
