import { type } from "arktype";

export * from "./palette";

export type Severity = "low" | "medium" | "high" | "critical";

// 'pending' = created, analysis not yet started.
// 'ready' = analysis complete, awaiting the user's generate selection.
// 'generating' = collateral generation actively running.
// The schema is the canonical definition (see SessionStatusSchema below); the
// type is derived from it so the union and the runtime validator never drift.
export type SessionStatus = typeof SessionStatusSchema.infer;

// The subset of artifact kinds the UI knows how to render exhaustively.
// The DB `kind` column is free-form text; this union stays closed for the
// CollateralBody renderer switch.
export type ArtifactKind =
  | "email"
  | "linkedin-post"
  | "twitter-post"
  | "blog"
  | "founder-pov-post"
  | "one-pager"
  | "case-study"
  | "objection-handling"
  | "customer-quotes"
  | "battlecard"
  | "pain-points"
  | "call-transcript"
  | "presentation";

export type ArtifactStatus = "draft" | "approved" | "rejected";

export const PainPoint = type({
  id: "string",
  workflowId: "string",
  severity: "'low' | 'medium' | 'high' | 'critical'",
  context: "string",
  quote: "string",
  selected: "boolean",
  createdAt: "string",
});
export type PainPoint = typeof PainPoint.infer;

// Provenance origins. Every artifact created on or after CL-2432 carries a
// non-null origin; `unknown` is reserved for legacy rows persisted before
// provenance was required (normalized at the serialization boundary).
export const artifactOrigins = [
  "workflow",
  "agent",
  "manual",
  "imported",
  "unknown",
] as const;
export type ArtifactOrigin = (typeof artifactOrigins)[number];

/**
 * Required "generated by" provenance on every artifact. `origin` is the
 * coarse producer class; `generatedBy` is a human-readable attribution (the
 * workflow name, agent name, or import label) surfaced as a gallery badge.
 * The index signature keeps producer-specific keys (e.g. `citations`,
 * `jobLabel`, `path`) without forcing every writer through one shape.
 */
export const ArtifactSource = type({
  origin: type.enumerated(...artifactOrigins),
  "generatedBy?": "string",
  "jobLabel?": "string",
  "[string]": "unknown",
});
export type ArtifactSource = typeof ArtifactSource.infer;

export const Artifact = type({
  id: "string",
  sessionId: "string | null",
  parentId: "string | null",
  painPointId: "string | null",
  kind: "string",
  title: "string",
  content: "string",
  status: "'draft' | 'approved' | 'rejected'",
  version: "number",
  ownerPrincipalId: "string | null",
  createdAt: "string",
  updatedAt: "string",
  source: ArtifactSource,
});
export type Artifact = typeof Artifact.infer;

export const ArtifactVersion = type({
  id: "string",
  artifactId: "string",
  version: "number",
  title: "string",
  content: "string",
  authorId: "string",
  createdAt: "string",
});
export type ArtifactVersion = typeof ArtifactVersion.infer;

/** An artifact with its full version history. */
export type ArtifactWithVersions = Artifact & { versions: ArtifactVersion[] };

/**
 * An artifact enriched with the session it belongs to. Returned by the
 * aggregate `GET /artifacts` endpoint so the library can show a "from" label
 * without a second round-trip.
 */
export type ArtifactWithSession = Artifact & {
  sessionName: string | null;
  sessionStatus: SessionStatus | null;
  ownerName: string | null;
};

// The closed set of session lifecycle states, shared by the boundary schemas
// below. `SessionStatus` is the inferred union; `SessionStatusSchema` is the
// arktype validator used wherever a status crosses a trust boundary.
export const SessionStatusSchema = type(
  "'pending' | 'analyzing' | 'ready' | 'generating' | 'reviewing' | 'done' | 'failed'",
);

/**
 * One row from `GET /workflow-runs` — a summary of a natively-deployed
 * workflow, used to populate the library rail. `status` is the free-form
 * `workflow_run.status` text, not a {@link SessionStatus}.
 */
export const WorkflowSummarySchema = type({
  id: "string",
  kind: "string",
  status: "string",
  createdAt: "string",
});
export type WorkflowSummary = typeof WorkflowSummarySchema.infer;

export const TranscriptInputSchema = type({
  transcript: "string",
  "source?": "'paste' | 'granola'",
});
export type TranscriptInput = typeof TranscriptInputSchema.infer;

export const WorkbenchSessionSchema = type({
  id: "string",
  transcriptId: "string",
  status: SessionStatusSchema,
  companyName: "string | null",
  createdAt: "string",
  updatedAt: "string",
});
export type WorkbenchSession = typeof WorkbenchSessionSchema.infer;

export const WorkflowStateSchema = type({
  id: "string",
  kind: "string",
  status: SessionStatusSchema,
  currentStep: "string",
  companyName: "string | null",
  // Generic per-step state. Each workflow's steps carry their own
  // inputs/outputs here under the step name; the host stays domain-agnostic.
  steps: { "[string]": "unknown" },
});
export type WorkflowState = typeof WorkflowStateSchema.infer;

export const AnalyzeRequestSchema = type({ transcript: "string" });
export type AnalyzeRequest = typeof AnalyzeRequestSchema.infer;

export const AnalyzeResponseSchema = type({
  workflowId: "string",
  painPoints: PainPoint.array(),
  status: SessionStatusSchema,
});
export type AnalyzeResponse = typeof AnalyzeResponseSchema.infer;

export const GenerateRequestSchema = type({
  workflowId: "string",
  painPointIds: "string[]",
});
export type GenerateRequest = typeof GenerateRequestSchema.infer;

export const GenerateResponseSchema = type({
  workflowId: "string",
  artifacts: Artifact.array(),
  status: SessionStatusSchema,
});
export type GenerateResponse = typeof GenerateResponseSchema.infer;

export const ImproveRequestSchema = type({
  artifactId: "string",
  feedback: "string",
});
export type ImproveRequest = typeof ImproveRequestSchema.infer;

export const ImproveResponseSchema = type({
  artifact: Artifact,
  status: SessionStatusSchema,
});
export type ImproveResponse = typeof ImproveResponseSchema.infer;

// Output-feedback (thumbs up/down). One canonical definition shared by the hub
// route, the web boundary parser, and the chat component.
//
// `workflow_step` is forward plumbing: the workflow-step rating surface is not
// wired into a UI yet, but the kind, schema, route handling, and DB column all
// carry it so adding that surface is purely additive.
//
// `feedbackSubjectKinds` is the readonly tuple the Drizzle `text` enum column
// needs; `FeedbackSubjectKindSchema` is the arktype validator. They are kept in
// lockstep so the DB enum and the wire schema can never drift.
export const feedbackSubjectKinds = ["turn_part", "workflow_step"] as const;

export const FeedbackSubjectKindSchema = type("'turn_part' | 'workflow_step'");
export type FeedbackSubjectKind = typeof FeedbackSubjectKindSchema.infer;

export const FeedbackRatingSchema = type("1 | -1");
export type FeedbackRating = typeof FeedbackRatingSchema.infer;

export const FeedbackRequest = type({
  subjectId: "string",
  subjectKind: FeedbackSubjectKindSchema,
  rating: FeedbackRatingSchema,
});
export type FeedbackRequest = typeof FeedbackRequest.infer;

export const SavedRating = type({
  subjectId: "string",
  subjectKind: FeedbackSubjectKindSchema,
  rating: FeedbackRatingSchema,
});
export type SavedRating = typeof SavedRating.infer;

export const FeedbackListResponse = type({ ratings: SavedRating.array() });
export type FeedbackListResponse = typeof FeedbackListResponse.infer;

// Per-member UI preferences, persisted server-side and shared by the hub route,
// the web boundary parser, and the Settings UI. Known keys are validated; the
// `[string]` index keeps the map open so a new preference needs no schema or DB
// migration (it just rides along in the jsonb blob). Every key is optional — a
// PATCH carries only what changed and is merged into the stored blob.
export const ToolSummaryStyleSchema = type(
  "'symbols' | 'natural' | 'detail' | 'varied' | 'mixed'",
);
export type ToolSummaryStyle = typeof ToolSummaryStyleSchema.infer;

// Kept in sync with the `Theme` union in `@workbench/ui`'s use-theme.ts (that
// package stays dependency-free, so the union is mirrored there, not imported).
export const ThemeSchema = type(
  "'corbits-dark' | 'corbits-light' | 'tkww' | 'notion'",
);
export type Theme = typeof ThemeSchema.infer;

export const MemberPreferences = type({
  "theme?": ThemeSchema,
  "compactToolActivity?": "boolean",
  "toolSummaryStyle?": ToolSummaryStyleSchema,
  "experimentalArtifactCards?": "boolean",
  // Run ids the member has archived (hidden by default) from the workflow-runs
  // list. Persisted per-member so the choice follows them across devices.
  "archivedWorkflowRuns?": "string[]",
  "[string]": "unknown",
});
export type MemberPreferences = typeof MemberPreferences.infer;
