import { type } from "arktype";

export * from "./palette";
export * from "./gate-mail-copy";
export * from "./myra-thread";
export * from "./active-context";
export * from "./attio-task-agent";
export * from "./ab-compare";
export * from "./gamma-presentation";
export * from "./gtm-scripts-briefs";
export * from "./governance";
export * from "./last30days";
export * from "./mailbox";
export * from "./mentions";
export * from "./now-feed";
export * from "./reddit-opportunity-scanner";
export * from "./scheduled-trigger";
export * from "./schedule-next-fire";
export * from "./routine-eligible";
export * from "./webhook-trigger";
export * from "./tasks";
export * from "./task-links";
export * from "./pain-point-collateral";
export * from "./multi-source-collateral";
export * from "./granola-call";
export * from "./sumble-account-intel";
export * from "./competitor-analysis";
export * from "./prospect-engine";

export * from "./web-site";
export * from "./preferences-registry";
export * from "./heartbeat-brief-merge";
export * from "./heartbeat-brief-title";
export * from "./heartbeat-brief-mail-refs";
export * from "./heartbeat-brief-document";
export * from "./mailbox-refs-header";
export * from "./changelog";
export * from "./deep-link";
export * from "./welcome-mail";
export {
  toHumanLabel,
  skillTitle,
  toAssetName,
  isSlugShaped,
} from "./tool-labels";
export { unwrapArgsEnvelope } from "./tool-args";
export {
  createToolLoopGuard,
  TOOL_LOOP_HINT_THRESHOLD,
  TOOL_LOOP_BLOCK_THRESHOLD,
  type ToolLoopGuard,
} from "./tool-loop-guard";
export {
  TOOL_ERROR_RECOVERY_GUIDANCE,
  withToolErrorRecoveryGuidance,
} from "./tool-error-recovery";

export type Severity = "low" | "medium" | "high" | "critical";

// 'pending' = created, analysis not yet started.
// 'ready' = analysis complete, awaiting the user's generate selection.
// 'generating' = collateral generation actively running.
// The schema is the canonical definition (see SessionStatusSchema below); the
// type is derived from it so the union and the runtime validator never drift.
export type SessionStatus = typeof SessionStatusSchema.infer;

// The subset of artifact kinds the UI knows how to render exhaustively.
// The DB `kind` column is free-form text; this union stays closed for the
// CollateralBody renderer switch.
export type ArtifactKind =
  | "email"
  | "linkedin-post"
  | "twitter-post"
  | "blog"
  | "founder-pov-post"
  | "one-pager"
  | "case-study"
  | "objection-handling"
  | "customer-quotes"
  | "battlecard"
  | "pain-points"
  | "call-transcript"
  | "presentation"
  | "gamma_presentation"
  | "skill-draft";

// Structured content stored in a `gamma_presentation` artifact. The DB `content`
// column holds the JSON serialization of this shape; hub writes it, web parses it
// to render the deck (iframe with a View-in-Gamma fallback).
export const GammaPresentationContentSchema = type({
  url: "string",
  description: "string",
  gammaId: "string",
});
export type GammaPresentationContent =
  typeof GammaPresentationContentSchema.infer;

export const PainPoint = type({
  id: "string",
  workflowId: "string",
  severity: "'low' | 'medium' | 'high' | 'critical'",
  context: "string",
  quote: "string",
  selected: "boolean",
  createdAt: "string",
});
export type PainPoint = typeof PainPoint.infer;

// Provenance origins. Every artifact created on or after CL-2432 carries a
// non-null origin; `unknown` is reserved for legacy rows persisted before
// provenance was required (normalized at the serialization boundary).
export const artifactOrigins = [
  "workflow",
  "agent",
  "manual",
  "imported",
  "unknown",
] as const;
export type ArtifactOrigin = (typeof artifactOrigins)[number];

/**
 * Required "generated by" provenance on every artifact. `origin` is the
 * coarse producer class; `generatedBy` is a human-readable attribution (the
 * workflow name, agent name, or import label) surfaced as a gallery badge.
 * The index signature keeps producer-specific keys (e.g. `citations`,
 * `jobLabel`, `path`) without forcing every writer through one shape.
 */
export const ArtifactSource = type({
  origin: type.enumerated(...artifactOrigins),
  "generatedBy?": "string",
  "jobLabel?": "string",
  "[string]": "unknown",
});
export type ArtifactSource = typeof ArtifactSource.infer;

export const Artifact = type({
  id: "string",
  parentId: "string | null",
  kind: "string",
  title: "string",
  content: "string",
  version: "number",
  ownerPrincipalId: "string | null",
  archivedAt: "string | null",
  createdAt: "string",
  updatedAt: "string",
  source: ArtifactSource,
});
export type Artifact = typeof Artifact.infer;

export const ArtifactVersion = type({
  id: "string",
  artifactId: "string",
  version: "number",
  title: "string",
  content: "string",
  authorId: "string",
  createdAt: "string",
});
export type ArtifactVersion = typeof ArtifactVersion.infer;

/** An artifact with its full version history. */
export type ArtifactWithVersions = Artifact & { versions: ArtifactVersion[] };

/**
 * An artifact enriched with the session it belongs to. Returned by the
 * aggregate `GET /artifacts` endpoint so the library can show a "from" label
 * without a second round-trip.
 */
export type ArtifactWithSession = Artifact & {
  sessionId: string | null;
  sessionName: string | null;
  sessionStatus: SessionStatus | null;
  ownerName: string | null;
};

// The closed set of session lifecycle states, shared by the boundary schemas
// below. `SessionStatus` is the inferred union; `SessionStatusSchema` is the
// arktype validator used wherever a status crosses a trust boundary.
export const SessionStatusSchema = type(
  "'pending' | 'analyzing' | 'ready' | 'generating' | 'reviewing' | 'done' | 'failed'",
);

/**
 * One row from `GET /workflow-runs` — a summary of a natively-deployed
 * workflow, used to populate the library rail. `status` is the free-form
 * `workflow_run.status` text, not a {@link SessionStatus}.
 */
export const WorkflowSummarySchema = type({
  id: "string",
  kind: "string",
  status: "string",
  createdAt: "string",
});
export type WorkflowSummary = typeof WorkflowSummarySchema.infer;

export const TranscriptInputSchema = type({
  transcript: "string",
  "source?": "'paste' | 'granola'",
});
export type TranscriptInput = typeof TranscriptInputSchema.infer;

export const WorkbenchSessionSchema = type({
  id: "string",
  transcriptId: "string",
  status: SessionStatusSchema,
  companyName: "string | null",
  createdAt: "string",
  updatedAt: "string",
});
export type WorkbenchSession = typeof WorkbenchSessionSchema.infer;

export const WorkflowStateSchema = type({
  id: "string",
  kind: "string",
  status: SessionStatusSchema,
  currentStep: "string",
  companyName: "string | null",
  // Generic per-step state. Each workflow's steps carry their own
  // inputs/outputs here under the step name; the host stays domain-agnostic.
  steps: { "[string]": "unknown" },
});
export type WorkflowState = typeof WorkflowStateSchema.infer;

export const AnalyzeRequestSchema = type({ transcript: "string" });
export type AnalyzeRequest = typeof AnalyzeRequestSchema.infer;

export const AnalyzeResponseSchema = type({
  workflowId: "string",
  painPoints: PainPoint.array(),
  status: SessionStatusSchema,
});
export type AnalyzeResponse = typeof AnalyzeResponseSchema.infer;

export const GenerateRequestSchema = type({
  workflowId: "string",
  painPointIds: "string[]",
});
export type GenerateRequest = typeof GenerateRequestSchema.infer;

export const GenerateResponseSchema = type({
  workflowId: "string",
  artifacts: Artifact.array(),
  status: SessionStatusSchema,
});
export type GenerateResponse = typeof GenerateResponseSchema.infer;

export const ImproveRequestSchema = type({
  artifactId: "string",
  feedback: "string",
});
export type ImproveRequest = typeof ImproveRequestSchema.infer;

export const ImproveResponseSchema = type({
  artifact: Artifact,
  status: SessionStatusSchema,
});
export type ImproveResponse = typeof ImproveResponseSchema.infer;

// Output-feedback (thumbs up/down). One canonical definition shared by the hub
// route, the web boundary parser, and the chat component.
//
// `workflow_step` is forward plumbing: the workflow-step rating surface is not
// wired into a UI yet, but the kind, schema, route handling, and DB column all
// carry it so adding that surface is purely additive.
//
// `feedbackSubjectKinds` is the readonly tuple the Drizzle `text` enum column
// needs; `FeedbackSubjectKindSchema` is the arktype validator. They are kept in
// lockstep so the DB enum and the wire schema can never drift.
export const feedbackSubjectKinds = ["turn_part", "workflow_step"] as const;

export const FeedbackSubjectKindSchema = type("'turn_part' | 'workflow_step'");
export type FeedbackSubjectKind = typeof FeedbackSubjectKindSchema.infer;

export const FeedbackRatingSchema = type("1 | -1");
export type FeedbackRating = typeof FeedbackRatingSchema.infer;

export const FeedbackRequest = type({
  subjectId: "string",
  subjectKind: FeedbackSubjectKindSchema,
  rating: FeedbackRatingSchema,
});
export type FeedbackRequest = typeof FeedbackRequest.infer;

export const SavedRating = type({
  subjectId: "string",
  subjectKind: FeedbackSubjectKindSchema,
  rating: FeedbackRatingSchema,
});
export type SavedRating = typeof SavedRating.infer;

export const FeedbackListResponse = type({ ratings: SavedRating.array() });
export type FeedbackListResponse = typeof FeedbackListResponse.infer;

// A persisted reference from a chat mail message to the file artifact its
// upload was diverted into. Attachments never ride inline on mail (the model
// would receive them — images inline, documents fail the turn), so the
// transcript chip is rehydrated from these workbench-owned references instead.
// `type` matches the ChatAttachment field name so refs render without mapping.
export const MailAttachmentRefSchema = type({
  mailId: "string > 0",
  artifactId: "string > 0",
  name: "string > 0",
  type: "string > 0",
  size: "number >= 0",
});
export type MailAttachmentRef = typeof MailAttachmentRefSchema.infer;

export const SaveMailAttachmentRefsRequest = type({
  mailId: "string > 0",
  attachments: type({
    artifactId: "string > 0",
    name: "string > 0",
    type: "string > 0",
    size: "number >= 0",
  })
    .array()
    .atLeastLength(1),
});
export type SaveMailAttachmentRefsRequest =
  typeof SaveMailAttachmentRefsRequest.infer;

export const MailAttachmentRefsResponse = type({
  refs: MailAttachmentRefSchema.array(),
});
export type MailAttachmentRefsResponse =
  typeof MailAttachmentRefsResponse.infer;

// Per-member UI preferences, persisted server-side and shared by the hub route,
// the web boundary parser, and the Settings UI. Known keys are validated; the
// `[string]` index keeps the map open so a new preference needs no schema or DB
// migration (it just rides along in the jsonb blob). Every key is optional — a
// PATCH carries only what changed and is merged into the stored blob.
export const ToolSummaryStyleSchema = type(
  "'symbols' | 'natural' | 'detail' | 'varied' | 'mixed'",
);
export type ToolSummaryStyle = typeof ToolSummaryStyleSchema.infer;

// Kept in sync with the `Theme` union in `@workbench/ui`'s use-theme.ts (that
// package stays dependency-free, so the union is mirrored there, not imported).
export const ThemeSchema = type(
  "'corbits-dark' | 'corbits-light' | 'tkww' | 'notion'",
);
export type Theme = typeof ThemeSchema.infer;

// One Gamma template as returned by `GET /gamma-templates`. Canonical wire
// shape shared by the hub route (emit + OpenAPI) and the web hook (parse) so
// the two can never drift. `canManage` is computed per-caller from the grant
// store; `description` is the human-facing label (the workflow owns generation
// instructions, not the template). `systemPrompt` is optional template-specific
// authoring guidance the generate step folds in alongside the base prompt
// empty string when the template author left it blank.
export const GammaTemplateSchema = type({
  id: "string",
  version: "number",
  name: "string",
  gammaId: "string",
  description: "string",
  systemPrompt: "string",
  authorId: "string",
  canManage: "boolean",
  createdAt: "string",
});
export type GammaTemplate = typeof GammaTemplateSchema.infer;

// Request body for create/update. `description` is required and non-empty
// (the server trims and rejects blanks); it is the one field the workflow does
// not need but humans do. `systemPrompt` is optional and may be blank.
export const GammaTemplateBodySchema = type({
  name: "string",
  gammaId: "string",
  description: "string",
  "systemPrompt?": "string",
});
export type GammaTemplateBody = typeof GammaTemplateBodySchema.infer;

// How far a member's Myra may go autonomously. `prepare_only` is the
// default posture: classify, plan, draft, read-only grounding — no writes.
// `execute_with_gates` lets Myra attempt tool writes, each still flowing
// through the existing approval rail; it never bypasses gates.
export const AgentAutonomySchema = type(
  "'prepare_only' | 'execute_with_gates'",
);
export type AgentAutonomy = typeof AgentAutonomySchema.infer;

// Resolves the effective autonomy for a member. The absent-value decision
// lives here, at the shared boundary, so every consumer agrees on the default.
export function resolveAgentAutonomy(prefs: MemberPreferences): AgentAutonomy {
  return prefs.agentAutonomy ?? "prepare_only";
}

export const MemberPreferences = type({
  "theme?": ThemeSchema,
  "agentAutonomy?": AgentAutonomySchema,
  "compactToolActivity?": "boolean",
  "toolSummaryStyle?": ToolSummaryStyleSchema,
  "experimentalArtifactCards?": "boolean",
  // The Attio workspace-member id/email this account maps to. Saved by the
  // Attio Task Agent workflow's member-selection gate so returning runs default
  // to "you" (and skip the picker) while staying switchable to another member.
  "attioMemberId?": "string",
  // Workflow kinds (the stable definition id) the member has favorited, in the
  // catalog. A patch replaces the whole array; favorites are pinned in the UI.
  "favoriteWorkflows?": "string[]",
  "[string]": "unknown",
});
export type MemberPreferences = typeof MemberPreferences.infer;

// --- Demos ---
// The Demos sidebar section is opt-in and HIDDEN by default. It is the mirror
// image of the workflow-run gate: that gate is allow-by-default and a `deny`
// grant disables a kind; demos are deny-by-default and an explicit member-role
// ALLOW on `demos`/`view` opts the org in. Enablement is that grant OR the hub
// `SHOW_DEMOS` env flag (a global override). When disabled the links never leave
// the hub — the client receives an empty list, so nothing to hide client-side.
export const DEMOS_RESOURCE = "demos";
export const DEMOS_VIEW_ACTION = "view";

// `icon` is a stable key the web client maps to a lucide component; an unknown
// key falls back to a generic icon, so adding a link never forces a client
// change. Icons are React components and cannot cross the API as values.
export const DemoLinkSchema = type({
  label: "string",
  href: "string",
  icon: "string",
});
export type DemoLink = typeof DemoLinkSchema.infer;

export const DEMO_LINKS: DemoLink[] = [
  {
    label: "Deal Scout",
    href: "https://deal-scout-abklabs.vercel.app/",
    icon: "search",
  },
  {
    label: "Notion Spike",
    href: "https://app-notion-spike.up.railway.app/",
    icon: "file-text",
  },
  {
    label: "Workbench (staging)",
    href: "https://workbench-ui-git-staging-abklabs.vercel.app/",
    icon: "flask",
  },
];

// Owner-area read/toggle for the org-wide demos grant. `enabled` reflects the
// member-role grant only. `forcedByEnv` is true when the `SHOW_DEMOS` env
// override is on — demos then show regardless of the grant, so the toggle has no
// effect and the UI says so instead of lying.
export const OwnerDemosResponse = type({
  enabled: "boolean",
  forcedByEnv: "boolean",
});
export type OwnerDemosResponse = typeof OwnerDemosResponse.infer;

export const OwnerDemosToggle = type({
  enabled: "boolean",
});
export type OwnerDemosToggle = typeof OwnerDemosToggle.infer;

// A single step in a workflow's flow, classified for the catalog preview:
// "auto" = a deterministic tool/fetch/export step, "agent" = a genuine LLM
// reasoning step, "human" = an awaitSignal gate that pauses for the user.
export const WorkflowFlowStepSchema = type({
  id: "string",
  title: "string",
  kind: "'auto'|'agent'|'human'",
  // The runtime step ids this entry represents, in run order (CL-4285). `id`
  // is a synthetic group key for a declared display-flow group (e.g.
  // "gather") — never assume it is itself a runtime step id. A run pane must
  // match a step's phase against `stepIds`, not `id`.
  stepIds: "string[]",
});
export type WorkflowFlowStep = typeof WorkflowFlowStepSchema.infer;

// One runnable workflow in the catalog, carrying everything the Workflows page
// needs to render its row and its step-flow preview without a further call:
// the member's favorite state, the classified step DAG, and the pause count.
// A workflow's first-intake form field, as surfaced to the attach UI so it can
// A workflow's first-intake form field, as surfaced to the attach UI so it can
// collect the intake payload a scheduled run is pre-filled with (CL-3509) and
// enriched for schema-driven schedule forms (CL-3860). Input kinds cover the
// form renderer; `fromProfile` marks fire-time profile-supplied fields.
// `string-array` supports multi-value verticals (prospect-engine schedule intake).
export const ScheduleFieldInputKindSchema = type(
  "'text' | 'textarea' | 'url' | 'select' | 'boolean' | 'string-array'",
);
export type ScheduleFieldInputKind = typeof ScheduleFieldInputKindSchema.infer;

export const ScheduleFieldOptionSchema = type({
  value: "string",
  label: "string > 0",
});
export type ScheduleFieldOption = typeof ScheduleFieldOptionSchema.infer;

export const ScheduleFieldMetadataSchema = type({
  name: "string > 0",
  label: "string > 0",
  /** Input control kind. Legacy packages may still use `kind` as the key. */
  "inputHint?": ScheduleFieldInputKindSchema,
  /**
   * Legacy alias for `inputHint` (CL-3509 INTAKE_FIELDS). Prefer `inputHint`.
   * When both are set, `inputHint` wins.
   */
  "kind?": ScheduleFieldInputKindSchema,

  "required?": "boolean",
  "placeholder?": "string",
  "help?": "string",
  /** Sort key ascending; missing order sorts after numbered fields (stable by name). */
  "order?": "number.integer",
  /** Select options when inputHint/kind is `select`. */
  "options?": ScheduleFieldOptionSchema.array(),
  /**
   * Key naming a live options source the hub resolves at render time (CL-4279),
   * e.g. a Sumble org list a workflow author cannot enumerate statically.
   * Mutually intended with `inputHint: "select"`; the hub's
   * `GET /schedule-field-options/:sourceId` route resolves this key to
   * `ScheduleFieldOption[]` — never Sumble- or provider-specific here, so any
   * future live-sourced field reuses the same mechanism.
   */
  "optionsSource?": "string > 0",
  /**
   * When set, fire-time merge supplies this value from the member profile; the
   * form renders the field read-only with a "from your profile" chip.
   */
  "fromProfile?": "string > 0",
});
export type ScheduleFieldMetadata = typeof ScheduleFieldMetadataSchema.infer;

/** Response body for the live schedule-field-options resolver route (CL-4279). */
export const ScheduleFieldOptionsResponseSchema = type({
  options: ScheduleFieldOptionSchema.array(),
});
export type ScheduleFieldOptionsResponse =
  typeof ScheduleFieldOptionsResponseSchema.infer;

/** @deprecated Prefer ScheduleFieldMetadataSchema — same shape, CL-3509 name. */
export const WorkflowIntakeFieldSchema = ScheduleFieldMetadataSchema;
export type WorkflowIntakeField = ScheduleFieldMetadata;

/** Resolve the effective input control for a field. */
export function scheduleFieldInputHint(
  field: ScheduleFieldMetadata,
): ScheduleFieldInputKind {
  return field.inputHint ?? field.kind ?? "text";
}

/**
 * Sort fields for form rendering: explicit `order` ascending, then name.
 * Pure — does not mutate the input array.
 */
export function sortScheduleFields(
  fields: readonly ScheduleFieldMetadata[],
): ScheduleFieldMetadata[] {
  return [...fields].sort((a, b) => {
    const ao = a.order ?? Number.MAX_SAFE_INTEGER;
    const bo = b.order ?? Number.MAX_SAFE_INTEGER;
    if (ao !== bo) return ao - bo;
    return a.name.localeCompare(b.name);
  });
}

/**
 * Fallback field list when a kind has intake schema names but no metadata
 * export: field name as label, text input. Metadata enriches, never gates.
 */
export function fallbackScheduleFields(
  fieldNames: readonly string[],
): ScheduleFieldMetadata[] {
  return fieldNames.map((name, i) => ({
    name,
    label: name,
    inputHint: "text" as const,
    order: i,
  }));
}

/**
 * True when every metadata field name is in the intake schema name set (catches
 * drift between scheduleFields and the arktype intake schema).
 */
export function scheduleFieldsMatchIntakeSchema(
  metadata: readonly ScheduleFieldMetadata[],
  intakeFieldNames: ReadonlySet<string>,
): boolean {
  return metadata.every((f) => intakeFieldNames.has(f.name));
}

/**
 * Build a trigger/run payload from draft form values: drops `fromProfile`
 * fields (fire-time merge supplies those), and drops undefined/null/blank
 * values so the payload only carries what the member actually filled in.
 * Shared by the create, edit, and run-once flows so all three send the same
 * shape to the hub.
 */
export function buildScheduleTriggerPayload(
  fields: readonly ScheduleFieldMetadata[],
  values: Record<string, unknown>,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};
  for (const field of fields) {
    if (field.fromProfile) continue;
    const v = values[field.name];
    if (v === undefined || v === null) continue;
    if (typeof v === "string" && v.trim() === "") continue;
    payload[field.name] = v;
  }
  return payload;
}

export const WorkflowCatalogEntrySchema = type({
  kind: "string",
  label: "string",
  "description?": "string",
  isFavorite: "boolean",
  stepCount: "number",
  pauseCount: "number",
  steps: WorkflowFlowStepSchema.array(),
  "lastRunAt?": "string",
  // Whether this kind can be attached to a brief schedule (CL-3508): true when it
  // runs to completion unattended — no human gates, or its only gate is `intake`
  // (pre-filled and auto-delivered). A kind with other human gates is false.
  attachable: "boolean",
  // The intake fields the attach UI collects for a requiresIntake kind (CL-3509);
  // absent for kinds that need no intake.
  "intakeFields?": WorkflowIntakeFieldSchema.array(),
  // Schedule scopes this kind accepts (CL-4110). Always present; non-attachable
  // kinds still report personal-only so the client never special-cases absence.
  allowedScopes: "('personal' | 'tenant')[]",
  defaultScope: "'personal' | 'tenant'",
});
export type WorkflowCatalogEntry = typeof WorkflowCatalogEntrySchema.infer;

// The whole Workflows-page catalog in one response — favorites already resolved
// and pinned first, steps already classified. Deliberately not paginated: the
// catalog is small and the page loads it in a single call.
export const WorkflowCatalogSchema = type({
  entries: WorkflowCatalogEntrySchema.array(),
});
export type WorkflowCatalog = typeof WorkflowCatalogSchema.infer;

// Maps a favorites list plus the run-history kinds onto catalog entries so the
// hub and any consumer share one ordering rule: favorites first (in favorites
// order), then the rest by label. Pure over its inputs.
export function orderCatalogEntries(
  entries: readonly WorkflowCatalogEntry[],
  favoriteKinds: readonly string[],
): WorkflowCatalogEntry[] {
  const favoriteRank = new Map<string, number>();
  favoriteKinds.forEach((kind, i) => favoriteRank.set(kind, i));
  return [...entries].sort((a, b) => {
    const aRank = favoriteRank.has(a.kind)
      ? (favoriteRank.get(a.kind) as number)
      : Infinity;
    const bRank = favoriteRank.has(b.kind)
      ? (favoriteRank.get(b.kind) as number)
      : Infinity;
    if (aRank !== bRank) return aRank - bRank;
    return a.label.localeCompare(b.label);
  });
}
